### ISSUE TITLE
Docs on CancelScope contradictory

### ISSUE THREAD

**Issue by Brandon-Jeffrey-Vibrant-Media** [python-trio/trio#1008]
In [https://trio.readthedocs.io/en/latest/reference-core.html](https://trio.readthedocs.io/en/latest/reference-core.html) the documentation on `CancelScope`s is contradictory. In the introduction it says:

> Cancel scopes are not reusable or reentrant; that is, each cancel scope can be used for at most one with block. (You’ll get a RuntimeError if you violate this rule.)

In the section on `cancelled_caught `it says:

> If the same CancelScope is reused for multiple with blocks, the cancelled_caught attribute applies to the most recent with block. (It is reset to False each time a new with block is entered.)

The first firmly states that the conditions described in the second are impossible.

**Comment by oremanj** [comment]
Well spotted! CancelScope was originally going to be reusable, but we removed that functionality because we realized it was going to close off some avenues for extension that we wanted to keep available.

Feel free to submit a PR to fix the docs, or I'll probably get to it in a few days if you don't.

**Comment by njsmith** [comment]
> I'll probably get to it in a few days if you don't.

Let's leave this as a good-first-issue, since we need to increase our supply between now and PyCon :-)

**Comment by njsmith** [comment]
(But anyone who's actually looking for a good first issue should still feel free to pick this up, even if you're not at PyCon.)
