### ISSUE TITLE
Add trio documentation to devdocs

### ISSUE THREAD

**Issue by math2001** [python-trio/trio#1031]
Over the past few days, I've been adding (locally) the `trio` documentation to [devdocs](https://devdocs.io), an "API Documentation Browser", and testing it out. It makes it much faster to search for functions and methods documentation, here's a quick gif:

![trio-devdocs](https://user-images.githubusercontent.com/15224242/56855356-0792ad80-6989-11e9-959b-af0c6a06a4e8.gif)

*Note: the icon is just local. Once merged into devdocs, it'll be the proper one*.

I figured I'd just make sure it's OK with everyone.

Here are the pages I've included:

- Trio’s core functionality
- I/O in trio
- Introspecting and extending Trio with trio.hazmat
- Testing made easier with trio.testing

All the other ones don't document any API, so I think people should refer to the real docs.

I'm not sure what the footer should be though. For each pages, `devdocs` displays a little footer with the copyright infos. For Python for example:

![image](https://user-images.githubusercontent.com/15224242/56855463-dadf9580-698a-11e9-9d4f-08142991a0d1.png)

I used this for trio:

```
© 2017-2019 Nathaniel J. Smith
Licensed under MIT and Apache2.
```

If that's good, then I think everything should be cool, and I can submit my PR :-)

@njsmith could you close this issue when you think everything's fine?

**Comment by njsmith** [comment]
Sounds good to me!

What's the mechanism for keeping the docs up to date as they evolve? Is it ingesting the sphinx docs directly, or...?

**Comment by math2001** [comment]
> What's the mechanism for keeping the docs up to date as they evolve? Is it ingesting the sphinx docs directly, or...?

Yep, it scraps the html and stores the different parts its interested in (so, when a user asks for the docs on devdocs, it doesn't re-ask the sphinx docs). To update a documentation, they have to bump the version manually, and it'll then re-scrap and update the cache.

**Comment by njsmith** [comment]
Hmm, too bad we can't automate it. But I guess if people are using it and it gets out of date, then they'll notice and we can deal with it then...

Anyway, sounds good and I don't think there's anything else to do, so hitting close as requested :-)

**Comment by pquentin** [comment]
The last time we talked about copyright year swe ended up deciding that we should keep 2017 forever: https://github.com/python-trio/trio/pull/510. Should we do the same in devdocs?
