### ISSUE TITLE
How to implement custom context manager classes.

### ISSUE THREAD

**Issue by pipermerriam** [python-trio/trio#1045]
I'm trying to implement something along the lines of the following pattern which seems like it should be allowable under the philosophy of trio but I cannot seems to figure out a clean way to do it.

I have a class which represents a *server* and I need to expose this API via two mechanisms which build on each other.

First, an `await start(nursery)` and `await stop()` API for manual starting and stopping.

```python
async def my_application():
    server = Server()
    async with trio.open_nursery() as nursery:
        await server.start(nursery)
        # ... do some things
        await server.stop()
```

However, the above API is better managed using a context manager since forgetting to call `stop` is probably bad and we might forget to implement proper error handling to ensure stop is called even in cases where exceptions are raised.   To remedy this I want to expose this API using an async context manager.

```python
async with Server():  # server starts on the way in
    # server is running in this context....
# server stops once context exits
```

In order for the server to be running I need to start the server on the way into the context manager and stop it on the way out.

The code below is my best stab at this so far.

```python
class Server:
    async def start(self, nursery):
        # This method lets us run the server with the expectation it would be explicitly stoped it later.
        nursery.start_soon(self.run)

    async def run(self):
        # long running
        while True:
            ...

    async def stop(self):
        # make the server stop
        ...

    async def __aenter__(self):
        nursery_manager = trio.open_nursery()
        nursery = await nursery_manager.__aenter__()
        await self.start(nursery)
        self._nursery_manager = nursery_manager

    async def __aexit__(self, exc_type, exc_value, exc_tb):
        try:
            await self.stop()
        finally:
            await self._nursery_manager.__aexit__(exc_type, exc_value, exc_tb)
```

This feels wrong.  I don't think I'm supposed to be interacting directly with the nursery manager class.  Any advice?

**Comment by smurfix** [comment]
Short version: You want a procedure with an @asynccontextmanager decorator. This is part of `contextlib` (Python 3.7) or, for earlier versions, `async_generator`.

If necessary, I can elaborate, but not today I'm afraid.

**Comment by tjstum** [comment]
+1 to @smurfix's suggestion. It's definitely possible to drive the context managers by hand, but it can be subtle and tricky to get exactly right.

I might suggest adding a function near your `Server` class that manages the server's lifecycle methods and the nursery together. Sort of like how trio's `open_nursery` works :-)

It might look something like this
```python
class Server:
    async def start(self, nursery):
        # This method lets us run the server with the expectation it would be explicitly stoped it later.
        nursery.start_soon(self.run)

    async def run(self):
        # long running
        while True:
            ...

    async def stop(self):
        # make the server stop
        ...

@contextlib.asynccontextmanager
async def open_server():
    async with trio.open_nursery() as nursery:
        server = Server(nursery)
        await server.start()
        try:
            yield server
        finally:
            await server.stop()  # you might be Cancelled here!

...
async with open_server() as server:
    # use server
```

That should take care of cascading the exceptions correctly as well!

**Comment by pipermerriam** [comment]
Thanks, I think the problem was me trying to cram them into the `Server` class and thus trying to cram this into `__aenter__` and `__aexit__`.  :+1:

**Comment by smurfix** [comment]
We might still have an open TODO here, which is to improve the docs so that this becomes more obvious.
