### ISSUE TITLE
Strange behaviour on FreeBSD

### ISSUE THREAD

**Issue by novel** [python-trio/trio#1050]
Looks like trio cannot poll file descriptors corresponding to devices in `/dev` on FreeBSD. Consider the following example:

```
#!/usr/bin/env python3.7

import asyncio
import sys

import trio

async def foo():
    lock = asyncio.Lock()
    async with lock:
        with open(sys.argv[1], 'r') as f:
            await trio.hazmat.wait_readable(f)
    

async def main():
    await foo()

if __name__ == "__main__":
    trio.run(main)
```

I can it use with e.g. text files:

```
$ ./trio_test.py /tmp/test.txt
$
```

But when i try to do it on some `/dev` entities, it fails:

```
$ ./trio_test.py /dev/random
Traceback (most recent call last):
  File "./trio_test.py", line 19, in <module>
    trio.run(main)
  File "/usr/local/lib/python3.7/site-packages/trio-0.11.0+dev-py3.7.egg/trio/_core/_run.py", line 1552, in run
    raise runner.main_task_outcome.error
  File "./trio_test.py", line 16, in main
    await foo()
  File "./trio_test.py", line 12, in foo
    await trio.hazmat.wait_readable(f)
  File "/usr/local/lib/python3.7/site-packages/trio-0.11.0+dev-py3.7.egg/trio/_core/_io_kqueue.py", line 131, in wait_readable
    await self._wait_common(fd, select.KQ_FILTER_READ)
  File "/usr/local/lib/python3.7/site-packages/trio-0.11.0+dev-py3.7.egg/trio/_core/_io_kqueue.py", line 120, in _wait_common
    self._kqueue.control([event], 0)
OSError: [Errno 19] Operation not supported by device
```

I tried to replicate this behavior using the C code:

```#include <sys/event.h>
#include <sys/time.h>

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int
main(int argc, char **argv)
{
   int f, kq, nev, ret = EXIT_FAILURE;
   struct kevent change;
   struct kevent event;

   if (argc != 2)
       return ret;

   kq = kqueue();
   if (kq == -1)
       perror("kqueue");

   f = open(argv[1], O_RDONLY);
   if (f == -1)
       perror("open");

   EV_SET(&change, f, EVFILT_READ, EV_ADD | EV_ONESHOT, 0, 0, 0);

   for (;;) {
       nev = kevent(kq, &change, 1, &event, 1, NULL);
       if (nev == -1)
           perror("kevent");
       else if (nev > 0) {
           printf("%s ready to read\n", argv[1]);
           ret = EXIT_SUCCESS;
           goto cleanup;
       }
   }

cleanup:
   close(kq);
   close(f);
   return EXIT_SUCCESS;
}
```

And it works fine for both text files and `/dev` entities:

```
$ ./a.out /dev/random 
/dev/random ready to read
$ ./a.out /tmp/test.txt 
/tmp/test.txt ready to read
$
```

PS Forgot provide version information:
FreeBSD 13.0-CURRENT amd64
Python 3.7.3
trio: today's git version (same behavior observed with 0.11 and Python 3.6)

**Comment by novel** [comment]
Hm, I noticed that my test application is not quite correct: `kevent()` call returns 1 event, but it has EV_ERROR, and in fact it has the same error: Operation not supported by device. Still not sure why in the python code it fails right away though.

**Comment by njsmith** [comment]
It sounds like the python kqueue wrapper is checking for `EV_ERROR` and converting it into an exception automatically, which seems reasonable.

Based on your last comment, it's looking like this is just a limitation of FreeBSD, and there's nothing Trio can do about it... Do you think there's something we could do differently?

**Comment by njsmith** [comment]
By the way, I doubt this is related but I'm surprised you don't get an error from using `asyncio.Lock` inside trio.

**Comment by oremanj** [comment]
asyncio.Lock appears to be compatible with everyone, even the World's Simplest Coroutine Runner, in the special case where there's no contention. (But @novel, you still shouldn't use it with Trio because it'll stop working as soon as you try to acquire an already-held lock -- that is, as soon as the lock provides you any benefit.)

**Comment by novel** [comment]
> It sounds like the python kqueue wrapper is checking for `EV_ERROR` and converting it into an exception automatically, which seems reasonable.
> 

I briefly looked at https://github.com/python/cpython/blob/master/Modules/selectmodule.c#L2135 and it seems there's no handling like that here, but maybe it's happening on higher level. I'll try to debug it further if I have time.

> Based on your last comment, it's looking like this is just a limitation of FreeBSD, and there's nothing Trio can do about it... Do you think there's something we could do differently?

Yeah, looks like a FreeBSD/kqueue limitation. Maybe it would make sense to provide some generic portable backend based on `select(2)` for example? But I'm not very familiar with Trio so not sure if that makes sense at all...

> By the way, I doubt this is related but I'm surprised you don't get an error from using asyncio.Lock inside trio.

Sorry for using that incorrectly, I was trying to quickly build some reproducer.

Thanks

**Comment by njsmith** [comment]
> I briefly looked at https://github.com/python/cpython/blob/master/Modules/selectmodule.c#L2135 and it seems there's no handling like that here, but maybe it's happening on higher level.

I'm guessing it's setting errno, and [ending up in `PyErr_SetFromErrno`](https://github.com/python/cpython/blob/af070c12970db34f004adf2e20306a285f06f3a9/Modules/selectmodule.c#L2158-L2161).

> Yeah, looks like a FreeBSD/kqueue limitation. Maybe it would make sense to provide some generic portable backend based on select(2) for example?

I would be very surprised if FreeBSD's `select` has superpowers that `kqueue` doesn't... I think inside the kernel they ultimately end up using the same code. Of course, software has surprised me before :-). If you want to make a check, I'll be curious to see the outcome...

In the mean time, it sounds like there's no todo item here, so I'm going to mark this closed. Feel free to re-open if you disagree or new information surfaces...
