### ISSUE TITLE
Doc s/we/xxx/; who are "we?"

### ISSUE THREAD

**Issue by dimaqq** [python-trio/trio#106]
Documentation uses "we" a lot, esp. in https://trio.readthedocs.io/en/latest/reference-core.html

It's ambiguous, it could be interpreted:
* "we the authors of trio library that you the developer are using," or
* "we the developers who write async functions"

Also, it seems "we" stands for several things:
* "We think this way is easier to reason about." -- sounds like "we who wrote trio"
* "then we propagate it." -- sounds like "trio runtime"
* "and we couldn’t get other stuff done" -- sounds like "we the async devs / end users"
* "when we exit the async with" -- sounds like "current thread of execution"

This ticket is to discuss classes of "we" and what "we" could be changed to.

**Comment by njsmith** [comment]
I guess I have a bit of a tic here, yeah :-). I just grepped through the docs and replaced a number of these with more specific words – does #113 make you happier?

**Comment by dimaqq** [comment]
Ugh, somehow I missed the PR; I see that it was mostly about yield/check point instead. I'm counting 2x we->you; 1x we->trio; 1x we->run; It's a good start!

**Comment by njsmith** [comment]
There do remain some "we" because it is a standard voice for tutorial-like stuff ("next we'll look at..."), and I like it :-). And also some places where it means "the trio authors" ("if you find a bug, let us know"). But if you spot any other places where it's confusing, let me (us? :-P) know.
