### ISSUE TITLE
MultiError.exceptions foils linter

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#1066]
Access of `exceptions` on a MultiError instance elicits "no-member" error from Pylint.

I believe it's because MultiError `__new__` is merely mutating the result of `BaseException.__new__(MultiError)`.  I'd address it by making a proper `__init__()` constructor.

**Comment by oremanj** [comment]
As I pointed out in that PR, using `__init__` with MultiError is tricky because of the behavior where `MultiError([e])` just returns `e`.

Is pylint happier if you write something like this?
```
class MultiError:
    exceptions = []
    # ... rest of class ...

del MultiError.exceptions
```

**Comment by belm0** [comment]
@oremanj thank you, would have taken me a long time to figure that out.

I'd rather put an explicit guard in init than a workaround which may only satisfy some linters.

At the least, trio should have an explicit test for the solitary MultiError case.
