### ISSUE TITLE
Increase sleep time leniency in test_timeouts.py

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#1081]
Currently we allow 20% error, but this run on macos on azure had 40% error: https://dev.azure.com/python-trio/trio/_build/results?buildId=598&view=logs

(See also: https://github.com/python-trio/trio/issues/200#issuecomment-498509115)

I guess we should bump the error threshold to 50%, by modifying this line of code:

https://github.com/python-trio/trio/blob/5ba7c569dc897777588f11ab37e51a648b493d74/trio/tests/test_timeouts.py#L35

to say `1.5` instead of `1.2`.

**Comment by epellis** [comment]
Just made a PR to fix this. Thanks for leaving easy issues like this for the newbies, I'll try to work on something bigger next!

**Comment by njsmith** [comment]
@epellis Excellent! If you want some help brainstorming things to work on, feel free to ask in [our chat](https://gitter.im/python-trio/general).
