### ISSUE TITLE
Optionally allow to set the thread's name where possible

### ISSUE THREAD

**Issue by thedrow** [python-trio/trio#1148]
This request is kind of specific to Celery's needs but I'm sure other's may agree this is worthwhile doing.

On platforms which support this behaviour (Linux, MacOS, *BSD, New versions of Windows) it is possible to set the thread's name (or description on Windows).

It requires some C/C++ or an optional dependency but shouldn't be that hard to implement.

**Comment by njsmith** [comment]
What do you mean by "set the threads name"? The [`name=` argument to `threading.Thread`](https://docs.python.org/3/library/threading.html#threading.Thread), or something else?

**Comment by thedrow** [comment]
The name keyword argument does not set the thread's name/description for the OS.
See [this](https://stackoverflow.com/a/51668422/85140) answer for the simplest way to do it on Linux.
A more portable way would be to use CFFI if available.

We would need to add a `name` keyword argument to `trio.run_sync_in_thread()` to do so.

**Comment by njsmith** [comment]
Huh, I'm surprised `prctl` isn't already wrapped in the stdlib somewhere. Seems like a reasonable thing to me. We could default to something like `f"Thread for {trio.hazmat.current_task().name}"`.
