### ISSUE TITLE
What happened to BlockingTrioPortal?

### ISSUE THREAD

**Issue by jtrakk** [python-trio/trio#1167]
It has disappeared in 0.12.0 but I don't see anything in the changelog. The PR seems to be [this one](https://github.com/python-trio/trio/commit/7f36105f1c0fec193e32813048283838b6e09a1c).

**Comment by njsmith** [comment]
Oh shoot, it was supposed to be deprecated in favor of the new `trio.from_thread` functions, but apparently we made some kind of mistake in the deprecation. It's supposed to still exist but give a warning; instead it doesn't exist at all.

**Comment by njsmith** [comment]
Oh heh, it accidentally got moved to `trio.hazmat` and I didn't notice during the review. See #1168

**Comment by jtrakk** [comment]
Should the `0.12.0` changelog mention the deprecation as well?

**Comment by njsmith** [comment]
@jtrakk Yeah, it totally should. It looks like when I was reviewing #1122, I had a total brain-fart and forgot to ask for a newsfragment! :man_facepalming: I've added that to the PR in #1168 as well.

**Comment by njsmith** [comment]
Btw, CC @epellis – none of this is your fault, it's my fault for missing it during the review, but still probably useful to look over.
