### ISSUE TITLE
Did you ever try googling Trio?

### ISSUE THREAD

**Issue by Tronic** [python-trio/trio#1211]
Google is notoriously good at guessing what I meant, and even generic nouns like [requests](https://www.google.com/search?q=requests), [pandas](https://www.google.com/search?q=pandas) and [anaconda](https://www.google.com/search?q=anaconda) get me directly to the Python things instead of the meanings that normal people would assign to such words.

It turns out that [trio](https://www.google.com/search?q=trio) as a name is a bit unfortunate. Google finds me restaurants and shopping centres instead of the library. Even when I try to be a bit more specific, such as [trio networking](https://www.google.com/search?q=trio+networking), my favourite project won't even show up on the first page.

Trio is not alone with this problem, as my [other favourite project](https://www.google.com/search?q=sanic) also seems to suffer of a similar issue:

![image](https://user-images.githubusercontent.com/98187/64911455-a4809800-d72a-11e9-8259-134d839609be.png)

**Comment by njsmith** [comment]
Requests and pandas are two of the most popular software packages in the world. Looking at pypistats.org, last month requests had 2000x more downloads than trio. Anaconda is a super popular software package and the name of a company with a marketing budget. I don't think there's a lot we can do about this except, like, get popular...?

In the mean time, searching "trio python" seems to give tons of relevant results, so at least it's possible to find info.

**Comment by Tronic** [comment]
👍to get popular 😋
