### ISSUE TITLE
use pidfd on Linux when available

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#1241]
Recent versions of the Linux kernel finally added a much more reasonable way to interact with subprocesses called "pidfd". The main advantages are:

- Using an fd as a handle for interacting with a process avoids a bunch of weird edge cases that pids have, like pids being recycled out from under you so you accidentally kill the wrong process (this isn't an issue for the specific way trio interacts with subprocesses, because we only work with child processes and the relationship between a parent and child is special, but in more general cases it's an issue)
- You can wait for child processes using `epoll`!!!!
- There may be more fancy features coming that are built on top of pidfd, like the ability to automatically kill a child when the last pidfd reference to it is closed.

Probably the epoll integration is the first thing we care about, since it provides an alternative to the rube goldberg thread-based construction we use now. Of course we'll still have to maintain that indefinitely because of RHEL and friends, but it'll be nice to avoid it when running on a modern system. That also means this isn't like, a huge urgent priority, because the user-visible impact is basically nil. But we'll want it eventually, so might as well have an issue to collect information until we're ready.

Initial pidfd support landed in kernel 5.1; the epoll integration landed in 5.3. And Ubuntu 19.10 (out next week) will have a 5.3 kernel, so pidfd is starting to actually filter out to users. I believe that in 19.10 there still aren't any glibc wrappers for the new syscalls, so if you want to access them you have to [call `syscall` directly](https://manpages.courier-mta.org/htmlman2/syscall.2.html). We could do that with ctypes or something though – it's janky but not difficult.

The biggest blocker here is that we will definitely need to test the new code, and AFAIK none of the CI services we have access to will ship a pidfd-capable kernel for... a while. They all seem to stick to LTS releases, and sometimes they're slow to upgrade even then... Azure is still on Ubuntu 16.04, though Travis and Github Actions both have 18.04. So probably we won't be able to actually *test* pidfd support until sometime after Ubuntu 20.04 LTS is released in April 2020. (Unfortunately since this is a kernel feature, using docker to pull down a newer release doesn't help, and I'm not aware of any hosted CI services that let you bring-your-own-kernel.)

**Comment by njsmith** [comment]
Python 3.9 will have a `os.pidfd_open` wrapper built-in: https://github.com/python/cpython/pull/17063

It's pretty simple so we might end up ignoring this and using cffi instead, in order to support older Python versions, but wanted to mention for reference.

**Comment by benjaminp** [comment]
Note you can obtain a pidfd by doing `open('/proc/PID', O_DIRECTORY)`. `pidfd_open` is mainly useful if you need to be robust against environments where `/proc` isn't mounted. Of course, to do anything useful with the pidfd you do need to make new syscalls, so that factoid may not save you writing your own ffi.

**Comment by njsmith** [comment]
Oh huh, good point :-). And we need fallback code anyway for old systems, so we could use that for environments where there's no `/proc`.

> to do anything useful with the pidfd you do need to make new syscalls, so that factoid may not save you writing your own ffi.

The number one motivation for using this would be to replace our current hack of spawning a thread for every child process just to sit and wait for notification that it's finished. To do that with pidfd, we don't need any other syscalls, just `await trio.hazmat.wait_readable(pidfd)`.

What I'm not sure of is how we can tell whether the fd we pulled out of `/proc` is actually a new-style pidfd that we can pass to epoll, or a regular old-style directory fd. Do you (or anyone) know of any behavioral differences we could use to sniff that out? I guess we could try to guess by parsing `os.uname().release` but I'd *really* prefer to avoid that if possible...

**Comment by brauner** [comment]
On November 7, 2019 9:32:20 AM GMT+01:00, "Nathaniel J. Smith" <notifications@github.com> wrote:
>Oh huh, good point :-). And we need fallback code anyway for old
>systems, so we could use that for environments where there's no
>`/proc`.
>
>> to do anything useful with the pidfd you do need to make new
>syscalls, so that factoid may not save you writing your own ffi.
>
>The number one motivation for using this would be to replace our
>current hack of spawning a thread for every child process just to sit
>and wait for notification that it's finished. To do that with pidfd, we
>don't need any other syscalls, just `await
>trio.hazmat.wait_readable(pidfd)`.
>
>What I'm not sure of is how we can tell whether the fd we pulled out of
>`/proc` is actually a new-style pidfd that we can pass to epoll, or a
>regular old-style directory fd. Do you (or anyone) know of any
>behavioral differences we could use to sniff that out? I guess we could
>try to guess by parsing `os.uname().release` but I'd *really* prefer to
>avoid that if possible...

You can only get pollable pidfds from pidfd_open(). To tell them apart a staftfs looking at the filesystem type should be enough. Proper pidfd_open() pidfds are anonymous inodes.

**Comment by njsmith** [comment]
Huh. You never know who's reading these github threads :-). @brauner Thanks for the info, and for implementing pidfd! It's a massive, massive improvement.

**Comment by njsmith** [comment]
I believe this bit of gibberish works to get a compatible version of `pidfd_open` across past and future Python versions:

```python
import sys
if sys.platform == "linux":
    try:
        # Python 3.9+
        from os import pidfd_open
    except ImportError:
        import os
        import ctypes
        _cdll_for_pidfd_open = ctypes.CDLL(None, use_errno=True)
        _cdll_for_pidfd_open.syscall.restype = ctypes.c_long
        _cdll_for_pidfd_open.syscall.argtypes = [
            ctypes.c_long,  # syscall number
            ctypes.c_int,   # fd
            ctypes.c_uint,  # flags
        ]
        __NR_pidfd_open = 434
        def pidfd_open(fd, flags):
            result = _cdll_for_pidfd_open.syscall(
                __NR_pidfd_open, fd, flags
            )
            if result < 0:
                err = ctypes.get_errno()
                raise OSError(err, os.strerror(err))
            return result
```

(Well, it doesn't try to support Python 2; the `sys.platform` check is wrong there, and maybe other things too. In case anyone cares about that. Fortunately Trio doesn't :-).)

**Comment by njsmith** [comment]
Except I'm not sure if those `argtypes` are correct. Maybe arguments to the libc `syscall` wrapper are always `long`, even when the underlying syscall takes `int`? The interaction of varargs and ABIs is super obscure so I'm not really sure, but the musl `syscall()` implementation does pull out the arguments using `va_arg(..., long)`.

**Comment by brauner** [comment]
> Huh. You never know who's reading these github threads :-). @brauner Thanks for the info, and for implementing pidfd! It's a massive, massive improvement.

Thank you for the kind words. :)
There is more to come. :)
