### ISSUE TITLE
Path should get the `__hash__` from `pathlib.PurePath`

### ISSUE THREAD

**Issue by georgeaf99** [python-trio/trio#1259]
`trio.Path`s don't exhibit the same hashing behavior as `pathlib.PurePath`

Repro (`python3.6.5` and `trio (0.11.0)`):
```
>>> from trio import Path
>>> hash(Path("foo"))
8743626168503
>>> hash(Path("foo"))
8743626168510
```

**Comment by oremanj** [comment]
Fixed by #1260. (@georgeaf99 FYI: if you put "Closes #1259" in the PR description, Github will close the issue automatically when the PR is merged.)
