### ISSUE TITLE
task calls reschedule on itself at nursery exit

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#1286]
Trio version 0.12.1

```python3
async def test_nursery_exit():
    class MyInstrument(trio.abc.Instrument):
        def __init__(self):
            self.rescheduled_from_self = False

        def task_scheduled(self, task):
            rescheduled_from = None
            try:
                rescheduled_from = trio.hazmat.current_task()
            except RuntimeError as e:
                assert str(e) == 'must be called from async context'
            print(f'task_scheduled {task.name} '
                  f'(rescheduled_from={rescheduled_from.name if rescheduled_from else None})')
            if rescheduled_from == task:
                traceback.print_stack()
                self.rescheduled_from_self = True

    instrument = MyInstrument()
    try:
        trio.hazmat.add_instrument(instrument)
        async with trio.open_nursery():
            pass
        assert not instrument.rescheduled_from_self
    finally:
        trio.hazmat.remove_instrument(instrument)
```
```
>           assert not instrument.rescheduled_from_self
E           assert not True
E            +  where True = <test_instrument.test_nursery_exit.<locals>.MyInstrument object at 0x101f9f438>.rescheduled_from_self

test_instrument.py:59: AssertionError
------------------------------- Captured stdout call -------------------------------
task_scheduled <test 'test_nursery_exit'> (rescheduled_from=<test 'test_nursery_exit'>)
------------------------------- Captured stderr call -------------------------------
...
  File "/.../python3.7/site-packages/trio/_core/_run.py", line 1769, in run
    run_impl(runner, async_fn, args)
  File "/.../python3.7/site-packages/trio/_core/_run.py", line 1930, in run_impl
    task._attempt_delivery_of_any_pending_cancel()
  File "/.../python3.7/site-packages/trio/_core/_run.py", line 1063, in _attempt_delivery_of_any_pending_cancel
    self._attempt_abort(raise_cancel)
  File "/.../python3.7/site-packages/trio/_core/_run.py", line 1052, in _attempt_abort
    self._runner.reschedule(self, capture(raise_cancel))
  File "/.../python3.7/site-packages/trio/_core/_run.py", line 1224, in reschedule
    self.instrument("task_scheduled", task)
  File "/.../python3.7/site-packages/trio/_core/_run.py", line 1609, in instrument
    method(*args)
  File "test_instrument.py", line 51, in task_scheduled
    traceback.print_stack()
```

**Comment by njsmith** [comment]
(Context: https://gitter.im/python-trio/general?at=5dbe800c9825bd6bac19c2d4)

OHH, I get it. OK yeah so this isn't a bug in trio, but it is potentially a problem for your hack.

What's happening is that after a task suspends itself, Trio immediately checks to see if there are any pending cancels for that task, and tries to deliver them. And it happens to do this *before* it changes the global state that `current_task()` looks at to mark that this task has suspended itself.

So I guess you could use this as an indication that a cancellation is being delivered?

**Comment by belm0** [comment]
I'm not sure I understand what the task_scheduled event corresponds to in this code:
```python3
async with trio.open_nursery():
    pass
```

**Comment by belm0** [comment]
OK, if I understand correctly:
  * a task always yields at nursery exit
  * it's the Trio core that will reschedule in this case
  * due to details of the instrument callbacks, current_task() happens to still hold the task at hand rather than raise an exception

**Comment by njsmith** [comment]
I think the nursery part is actually a red herring, and you'll also get it for a plain `await trio.sleep(0)`

**Comment by njsmith** [comment]
Or any other case where a task tries to go to sleep but immediately gets woken by a cancellation.

**Comment by belm0** [comment]
The misrepresentation by `current_task()` seems to be a general problem though.  It's only by way of the previous examples being trivial, with no other tasks to schedule, that current_task() happens to match scheduled task in the callback.  In general it will be "the previously scheduled task".

Here the reschedule at nursery exit is attributed to "trio.sleep":
```python3
async def test_nursery_exit():
     async with trio.open_nursery() as nursery:
        nursery.start_soon(trio.sleep, 1)
```
```
task_scheduled trio.sleep (rescheduled_from=<test 'test_nursery_exit'>)
task_scheduled trio.sleep (rescheduled_from=None)
task_scheduled <test 'test_nursery_exit'> (rescheduled_from=trio.sleep) ***
```

So I have no way to correctly attribute it to Trio core.

**Comment by njsmith** [comment]
@belm0 I mean... it is in fact the `sleep` completing that directly triggered the parent to wake up and continue? Isn't this exactly the kind of causal link you're looking for?

**Comment by belm0** [comment]
I think you are correct.  For example, if it wasn't sleep but some blocking code that we want to virtually speed up, then when the nursery is exited we *don't* want to apply the artificial delay, and the presence of a "rescheduled_from" task correctly cues that.
