### ISSUE TITLE
remove_instrument() should tolerate unregistered instrument?

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#1287]
Since registered instruments can be automatically removed on exception (presumably because an instrument error should not stop the program), it follows that `remove_instrument()` should probably tolerate the given instrument having already been removed.

**Comment by njsmith** [comment]
I can see the argument, but I can also see an argument that if your instrument got unceremoniously discarded, then maybe you want to know that? It does have well-defined, documented behavior in this case (raising `KeyError`).

**Comment by belm0** [comment]
Actually, what I'd prefer is that the instrument system not do this magic and simply raise an unhandled exception.  Instruments can be arbitrarily complex and manage invariants which the rest of the runtime depends on, so it seems arbitrary to expect that the program can continue properly without the instrument.

**Comment by njsmith** [comment]
So there are two reasons I did this weird log-and-swallow thing. One is that I was imagining instruments should generally be used for stuff like low-impact introspection (e.g. gathering metrics on a production system), where it's not ok if a typo takes down everything. (And I'm kind of ok with them being uncomfortable for managing actual critical program state – if you have something like that that needs an instrument, then low-level hooks like this are always going to be fragile and awkward, so we should probably extend the runtime or find another solution.)

And the other reason is that instruments execute in lots of really weird and fragile contexts, so I'm not actually sure *how* to reliably raise an exception. We definitely can't just let the exception leak out naturally – that would produce all kinds of undefined behavior, and require careful analysis at every instrument call site. We could inject it back into "user space" like we do with `KeyboardInterrupt` and then let the exception bubble out naturally, but that only works if the overall runtime/scheduling system is working, and if the goal is to better support instruments that provide critical runtime services, then by assumption we can't assume the runtime is working...

**Comment by belm0** [comment]
Fair enough, thank you for explaining.
