### ISSUE TITLE
How-to guides

### ISSUE THREAD

**Issue by jtrakk** [python-trio/trio#1291]
["What nobody tells you about documentation"](https://www.divio.com/blog/documentation/) distinguishes four types of documentation:

- tutorials,
- how-to guides,
- explanation,
- reference.

Of these, Trio docs are weakest on the "how-to guides" section. Currently there are a lot of hidden gems in chat, gists, and issues. That may be because Trio's evolving too quickly to have a stable set of how-tos. But as the API settles it would be nice to have vetted answers to common "how do I ___?" situations. 

Even before 1.0 it would be nice to display the current status of each how-to so I don't have to keep track of the mental bookmarks I've saved for each task, and ask on chat to makes sure the 2-year-old gist is still the preferred way.

Also nice: having recommendations tested in CI so they don't fall out of date. 

That includes how-tos which may involve third-party libraries, like triopg or asyncssh. 

Some examples include: "How do I"...

- [make line streams](https://github.com/python-trio/trio/issues/796#issuecomment-471428274)
- [crawl the web](https://gist.github.com/njsmith/432663a79266ece1ec9461df0062098d)
- [schedule jobs](https://gist.github.com/njsmith/432663a79266ece1ec9461df0062098d)
- make a Trionic process-pool executor
- interact with a repl, pexpect-style
- and many more...

**Comment by njsmith** [comment]
I think this is a duplicate of #472?

**Comment by jtrakk** [comment]
Yep.

**Comment by njsmith** [comment]
BTW, that was also inspired by that post – it's a pretty good post, isn't it? :-)

If you have a minute, it'd be great if you could check #472 and make sure all your ideas for howto topics are captured there – we don't want to lose those!

**Comment by N-Coder** [comment]
I'd be interested in seeing the example for "interact with a repl, pexpect-style", but couldn't find anything in the other issue.
