### ISSUE TITLE
AssertionError when I exit() semi-inside a nursery

### ISSUE THREAD

**Issue by jtrakk** [python-trio/trio#1305]
Like some of [these](https://github.com/python-trio/trio/issues/1056) maybe I'm supposed to get a `TrioRuleViolatedException`? `AssertionError` doesn't seem right. (An especially interesting perspective on assert [comes from sqlite](https://www.sqlite.org/assert.html)).

```py
import sys


import trio

async def f():
    print('hello')

@trio.run
async def main():
    async with trio.open_nursery():
        ctx = trio.open_nursery()
        n = await ctx.__aenter__()
        n.start_soon(f)
        sys.exit()

```
```
trio/_core/_run.py", line 607, in _nested_child_finished
    assert popped is self
AssertionError

```

**Comment by belm0** [comment]
Well, use of `assert` is correct inasmuch as the author of the library code expects it to be True for the remaining code to be valid.  Now it may be that the library user can induce the particular assertion failure-- that really depends on all the details of the implementation-- and if so then it's time to replace the assert with raising of an error meaningful to the user.

**Comment by oremanj** [comment]
Yep, nurseries don't support being used in a way that doesn't mimic the stack discipline of a real `async with` statement. See #1243 and #1056 for more discussion. Closing this since I don't think there's a remaining action item not covered by those other issues.
