### ISSUE TITLE
Efficient instrument implementation

### ISSUE THREAD

**Issue by jtrakk** [python-trio/trio#1340]
[From this comment](https://trio.discourse.group/t/eliot-the-causal-logging-library-now-supports-trio/167/14): 
> It’s true that the current implementation still adds unnecessary overhead for operations you haven’t hooked, but that’s just because we’re lazy and were waiting for someone to complain.

I'm not sure what's involved here but I wouldn't want a potentially significant improvement to get lost in a comment. :-)

**Comment by oremanj** [comment]
This is less severe than it sounds, because we already avoid the overhead if the user has *no* instruments configured. Still worth tracking though!
