### ISSUE TITLE
Comunicate a BLE from a graphical interface with qtdesigner

### ISSUE THREAD

**Issue by Vichooliva** [python-trio/trio#1385]
I'm trying to make a graphical interface that send some instructions when i clicked a button.

I tried to communicate different classes but the only way that the program lets me to do that is putting the async function inside the `__init__` function like this:

```
class funciones_asincronas(QObject):
    def __init__(self):
        async def run(self):
            print("iniciando busqueda")
            devices = await discover()   
            i=0
            direccion=[]
            time.sleep(1)
            print("Dispositivos encontrados:")
            for d in devices:
                if d.name!="HMSoft":
                    i=i
                    print("nada")
                else:
                    await direccion.append(d.address)
                    print(i,")",direccion)
                    i+=1              
        loop = asyncio.get_event_loop()
        loop.run_until_complete(run(self))
```

The way I call this class is this:

```
        self.btnReconectar.clicked.connect(funciones_asincronas)
```

And when i put "pass" in the `__init__` function, and make the async function outside the `__init_` it sent me the error that the "run(self)" from the loop stuff is not defined.

Can you please help me?

**Comment by njsmith** [comment]
This is the issue tracker for Trio. Trio and asyncio are different and incompatible ways of doing async code in Python. You're using asyncio, not Trio. So we can't help you here, sorry! (Also, Trio doesn't work with Qt right now anyway, so you couldn't use Trio even if you wanted to...)

Maybe try stackoverflow or something? Good luck!
