### ISSUE TITLE
Nursery/cancellation scopes do not allow for completion of `__aexit__` cleanup code with checkpoints

### ISSUE THREAD

**Issue by gesslerpd** [python-trio/trio#1389]
I am going to try and explain this issue through 3 example scenarios that exist in the `main` function below.

In all scenarios, I would expect the `print('exited', i)` to be run to signify completion of some async cleanup code.

There are comments above each scenario detailing the results observed in each.

I am starting to see a pattern with cancellation handling that is preventing the async cleanup code from running somehow. Note that `print('exiting', i)` was run in each failed scenario but code does not run after hitting the first trio checkpoint.

```python
from contextlib import asynccontextmanager

@asynccontextmanager
async def test(i):
    print('entering', i)
    await trio.sleep(1)
    print('entered', i)
    try:
        yield
    finally:
        print('exiting', i)
        await trio.sleep(1)
        print('exited', i)

async def task():
    async with test(1):
        print('yield')
        await trio.sleep(10)

async def main():
    # scenario 1
    # this task exits cleanly, even with KeyboardInterrupt after "yield"
    await task()
    
    # scenario 2
    # these tasks do not exit cleanly, with cancellation or KeyboardInterrupt after "yield"
    async with trio.open_nursery() as nursery:
        nursery.start_soon(task)
        nursery.start_soon(task)
        await trio.sleep(5)
        nursery.cancel_scope.cancel()
    
    # scenario 3
    # this task does not exit cleanly, with cancellation scope
    # this task exits cleanly, with KeyboardInterrupt after "yield"
    with trio.move_on_after(5):
        await task()

if __name__ == '__main__':
    trio.run(main)
```

**Comment by smurfix** [comment]
Your assumption is wrong. If you have an `await` inside a `finally` or `except BaseException` clause, you need to shield it. Otherwise it will re-raise the cancellation.

**Comment by smurfix** [comment]
… we probably need a "common pitfalls" section in the docs.

**Comment by gesslerpd** [comment]
Ok thanks for the response! Note that also classes implementing the `__aexit__` function also suffer from this pitfall.

Is there any way that you know of to shield something from cancellation without having a reference to a particular cancel scope?

**Comment by gesslerpd** [comment]
Never mind the previous comment, I just realized that I can add an inner cancel scope to the `__aexit__` to shield it from all outer calling scopes.

Thanks again!

**Comment by smurfix** [comment]
You don't need a reference to the scope you want to shield yourself from. You simply write
```
try:
    …
finally:
    with trio.CancelScope(shield=True):
        await my_cleanup()
```
