### ISSUE TITLE
Opening/Reading character device

### ISSUE THREAD

**Issue by joernheissler** [python-trio/trio#1395]
Hello,
I tried reading `/dev/input/event0` with trio. This character device generates a byte stream of events.
Only function I could find is `trio.open_file`, but looks like its purpose is actual files.
How can I open a character device so I'll get some `trio.abc.ReceiveStream`?

Thanks!

**Comment by pquentin** [comment]
A shot in the dark: would FdStream help? https://trio.readthedocs.io/en/stable/reference-hazmat.html#unix-specific-api

**Comment by njsmith** [comment]
Yeah, Trio doesn't have a pre-existing wrapper for /dev/event so you need
to know a bit about the lower-level Unix primitives, but here it's pretty
simple. In Unix, character devices general are "selectable", meaning that
they're set up to be used with the non-blocking io positives. (Unlike e.g.
regular on-disk files, which is what trio.open_file is mostly targeted at.)
And trio.hazmat.FdStream is already set up to handle Unix "selectable"
files.

So you want to do something like:

def open_events(events_dev_path):
    return trio.hazmat.FdStream(os.open(events_dev_path, os.O_RDONLY))

(Note the use of os.open to get raw file descriptor, versus using regular
open which would give us a Python file object. This is to avoid FdStream
and the file object from fighting over who's in charge of closing the file
descriptor.)

I'm assuming here that opening a /dev/event object is effectively
instantaneous. If it can block for some reason then you might want to wrap
the actual open call in a trio.to_thread.run_sync.

**Comment by joernheissler** [comment]
Thanks, I wasn't aware of `trio.hazmat.FdStream`. Works like a charm: https://gist.github.com/joernheissler/b366aae6b5067a5d71b2e46a5e6d5d63

I think it would still be great to have a function which handles `os.open` and `trio.hazmat.FdStream` for the user.

**Comment by oremanj** [comment]
The combination of os.open() + wrapping in FdStream that is possible with Trio's actual current APIs would only work for some devices and named pipes, not most files on disk (nor stdin, for example). I think exposing a nice name for this combo might become a bit of an attractive nuisance wrt users expecting more from it than it's able to deliver.

Closing this in favor of #174 and #219 which discuss the more general problem of wrapping "anything you can open" in a nice API.
