### ISSUE TITLE
Travis fails on Linux Python development versions

### ISSUE THREAD

**Issue by pquentin** [python-trio/trio#1402]
See https://travis-ci.org/python-trio/trio/builds/648727502 for an example. The failure occurs before we can do anything about it, it's Travis who's running the failing `pip --version` call.

I opened https://travis-ci.community/t/python-development-versions-no-longer-include-pip/7180 and wrote to Travis support. Our options:

 * wait for a fix from Travis
 * allow failures in those builds for a few days (they're "only" dev builds)
 * install Python development versions from git

I'd like to wait for a fix to see if the nightly build is fixed. If it's not fixed, then I'd like to allow failures until next Monday. If it's still an issue next Monday, then we'll figure out what to do.

**Comment by njsmith** [comment]
The Travis-mandated `pip --version` is failing, *but* that's not why the build is failing... travis ignores that failure and continues on. The build doesn't actually fail until we call `pip` ourselves, inside our test script that has the shell's abort-on-error feature enabled. So I guess we might be able to work around this? maybe `python -m ensurepip` or using [get-pip](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py)? Of course it might not be worth it if they'll fix it before we wake up tomorrow...

**Comment by pquentin** [comment]
(I updated my message above to fix the link to the Travis report.)

Apparently virtualenv 20 is a complete rewrite with a bunch of bugs, but they get fixed really quickly, including the one that we care about here: https://github.com/pypa/virtualenv/issues/1576

@BanzaiMan mentions that the next build will kick-off within the next 24 hours, which should hopefully fix the bug.
