### ISSUE TITLE
How to get "trio token" for trio.to_thread.run_sync?

### ISSUE THREAD

**Issue by Nikratio** [python-trio/trio#1439]
Hello,

I am trying to migrate from trio.BlockingTrioPortal to trio.from_thread(). Unfortunately I am running into some trouble because I am trying to call from a not-trio-created thread.

The documentation specifies that I can "pass a keyword argument, trio_token specifiying a specific trio.run loop to re-enter". But how do I get such a token? It doesn't seem mentioned anywhere else (including the description of trio.run).

I think I am looking for a function like `trio.get_current_token()` whose output I can save and pass to a thread for use with `trio.from_thread.run_sync.

**Comment by oremanj** [comment]
Use `trio.hazmat.current_trio_token()` from within the Trio thread. For more details, see https://trio.readthedocs.io/en/stable/reference-hazmat.html#trio-tokens

**Comment by njsmith** [comment]
Sounds like the docs could use a small update to point to that?

**Comment by Nikratio** [comment]
Yeah, a pointer would be great. I still feels somewhat counterintuitive that I have to fallback on `trio.hazmat` though, especially because with the old interface that wasn't necessary.

**Comment by pquentin** [comment]
@Nikratio We renamed hazmat to lowlevel recently to emphasize the fact that there's nothing wrong with that module :)
