### ISSUE TITLE
Windows non-IFS LSP build fails with SSL error when downloading .exe file

### ISSUE THREAD

**Issue by pquentin** [python-trio/trio#1478]
It fails at downloading the following .exe:

```
+ curl -fL --connect-timeout 5 -o lsp-installer.exe http://download.pctools.com/mirror/updates/9.0.0.2308-SDavfree-lite_en.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Why an SSL error? Well, the above link redirects to https://origin-download.nbu.nortonlifelock.com/mirror/updates/9.0.0.2308-SDavfree-lite_en.exe. Firefox is happy with the DigiCert SSL certificate, though, so I don't know what's going on. And my local curl works too...

**Comment by njsmith** [comment]
I guess we could just use `--insecure` here or something? We're using an `http://` link to start with, and the whole point of that test config is to install some highly dubious software on a scratch machine, so I think this is one of those incredibly rare cases where cert checking really isn't doing anything useful...

**Comment by njsmith** [comment]
This affected #1296. I just hit "re-run" to see if it's consistent...
