### ISSUE TITLE
Enable hoverxref in Trio docs

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#1522]
docs:

https://sphinx-hoverxref.readthedocs.io/en/latest/index.html

example:

![image](https://user-images.githubusercontent.com/609896/82013018-18fb3600-962e-11ea-81f9-e98eab9bf32d.png)

**Comment by Zac-HD** [comment]
Also https://sphinx-codeautolink.readthedocs.io/en/latest/, [here's the Hypothesis configuration](https://github.com/HypothesisWorks/hypothesis/blob/70b713a546e012685160e4cc27868b2aa2442c2d/hypothesis-python/docs/conf.py#L111-L116).

**Comment by kachida** [comment]
Hi @jakkdl  @CoolCat467 I've created a pull request (PR#2968) for this issue. Could you please take a look and review it?

Here's the link to the PR: [PR#2968](https://github.com/python-trio/trio/pull/2968)
