### ISSUE TITLE
Installation fails due to conflicting numpy version

### ISSUE THREAD

**Issue by NeolithEra** [python-trio/trio#1563]
Hi, users are unable to run Trios due to dependency conflict with _**numpy**_ package. As shown in the following full dependency graph of Trios, Trios requires _**numpy==1.13.3**_，while tifffile * requires _**numpy>=1.15.1**_.

According to pip’s “first found wins” installation strategy, _**numpy 1.13.3**_ is the actually installed version. However, _**numpy 1.13.3**_ does not satisfy _**numpy>=1.15.1**_.

### Dependency tree-----------
```
trios - 2.1
| +- cffi(install version:1.10.0 version range:==1.10.0)
| +- cython(install version:0.26.1 version range:==0.26.1)
| +- numba(install version:0.35.0 version range:==0.35.0)
| +- numpy(install version:1.13.3 version range:==1.13.3)
| +- pillow(install version:7.1.1 version range:*)
| +- scikit-image(install version:0.13.1 version range:==0.13.1)
| | +- astropy(install version:4.0.1.post1 version range:*)
| | +- dask(install version:2.14.0 version range:>=0.5.0)
| | +- imageio(install version:2.8.0 version range:*)
| | | +- numpy(install version:1.13.3 version range:*)
| | | +- pillow(install version:7.1.1 version range:*)
| | +- imread(install version:0.7.4 version range:*)
| | +- matplotlib(install version:3.2.1 version range:>=1.3.1)
| | | +- cycler(install version:0.10.0 version range:>=0.10)
| | | | +- six(install version:1.14.0 version range:*)
| | | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | | +- numpy(install version:1.13.3 version range:>=1.11)
| | | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| | +- networkx(install version:2.4 version range:>=1.8)
| | | +- decorator(install version:4.4.2 version range:>=4.3.0)
| | +- numpy(install version:1.13.3 version range:>=1.11)
| | +- pillow(install version:7.1.1 version range:>=2.1.0)
| | +- pyside(install version:1.2.4 version range:*)
| | +- pywavelets(install version:1.1.1 version range:>=0.4.0)
| | +- scipy(install version:0.19.1 version range:>=0.17.0)
| | +- simpleitk(install version:1.2.0 version range:*)
| | +- six(install version:1.14.0 version range:>=1.7.3)
| | +- tifffile(install version:2020.2.16 version range:*)
| | | +- imagecodecs(install version:2020.2.18 version range:>=2020.1.31)
| | | | +- numpy(install version:1.18.2 version range:>=1.15)
| | | +- numpy(install version:1.18.2 version range:>=1.15.1)
| +- scikit-learn(install version:0.19.1 version range:==0.19.1)
| +- scipy(install version:0.19.1 version range:==0.19.1)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Loosen the version range of **_numpy_** to be **_>=1.13.3_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_tifffile_**.
@njsmith Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by oremanj** [comment]
You've reached the issue tracker for the `trio` package, which is an async I/O framework with no dependency on numpy. It sounds like you're having trouble with the unrelated `trios` package. You're likely to have better luck contacting the `trios` developers or issue tracker; we `trio` folks can't help you with your problem.

**Comment by njsmith** [comment]
It looks like you're trying to install the "trios" package, and this is the
bug tracker for the "trio" package. Despite the confusingly similar names,
the two projects are unrelated. Were you looking for the machine learning
library or the concurrency framework?
