### ISSUE TITLE
Make a standard cookiecutter template for trio projects

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#158]
Can keep it pretty minimal because people all have their own ideas of how things should work, but I think there's enough little things that it could help with to be worthwhile:

- sphinxcontrib-trio set up

- CI setup similar to trio's own (in particular linux/mac/windows + pypy testing is not trivial... maybe not everyone wants it, and you can always turn it off, but I bet a lot of people would appreciate it)

- pytest-trio set up (well, need to extract it first... #27)

- a `~=` dependency on trio

- `python_requires`

I've never actually done anything with cookiecutter so no idea how difficult this will be, but it doesn't look too bad.

If anyone's looking to contribute but doesn't feel ready to dive into coroutine-land, then this would be a good place.

**Comment by njsmith** [comment]
Maybe it can also nag the user to subscribe to #1

**Comment by Fuyukai** [comment]
Since this got made (https://github.com/python-trio/cookiecutter-trio), closing.
