### ISSUE TITLE
to_thread.run_sync() foils meta-class destructors 

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#1638]
Invoking `to_thread.run_sync()` seems to prevent meta-class destructors of completely unrelated classes from being called on shutdown.

```python
import trio

class deltype(type):
    def __del__(self):
        print(f"{self.__name__} class deleted")

Test = deltype("Test", (object,), {})

async def async_main():
    await trio.to_thread.run_sync(lambda: print('hi'))
    await trio.sleep(0)

trio.run(async_main)
```

expected output:
```
hi
Test class deleted
```

actual output:
```
hi
```

if the `run_sync()` is commented out, the meta-class destructor is called as expected:
```
Test class deleted
```

**Comment by smurfix** [comment]
"git bisect" says the thread cache is the culprit.

1d1f871153b636fb18efe7091f7382e4fa57c41d

**Comment by smurfix** [comment]
That was reasonably easy ;-)
