### ISSUE TITLE
Allow passing a local address and address family to `trio.open_tcp_stream`

### ISSUE THREAD

**Issue by ntninja** [python-trio/trio#1642]
Given a DNS-name `trio.open_tcp_stream` currently has no way to limit the TCP connection to either IPv4 or IPv6 and has no way to bind the local socket to a specific interface or port. While this is not an issue in general and trio's native happy-eyeballs support is awesome, there are some advanced use cases where being more restrictive can be useful.

To that point there is currently [a patch proposed for `httpcore`/`httpx`](https://github.com/encode/httpcore/pull/100) that allows overriding the `local_addr` and `family` parameters globally for a connection pool. It's [missing trio support however](https://github.com/encode/httpcore/pull/100/files#diff-cbeba3dc15f25d038864dee6154cd4fbR146-R147) as trio does not support the require parameters.

**Comment by njsmith** [comment]
#275 is our canonical issue for discussing this feature – let's continue conversation there.
