### ISSUE TITLE
CI: sketchy Komodia LSP link stopped working

### ISSUE THREAD

**Issue by oremanj** [python-trio/trio#1667]
See #1666. I wonder if they noticed an uptick in the frequency of it being downloaded...

I have the installer binary, but no good place to host it.

**Comment by njsmith** [comment]
Simplest thing would be to stick it in a GitHub repo or "release".

**Comment by oremanj** [comment]
I set up a `python-trio/trio-ci-assets` repository and uploaded a lightly encrypted version of the installer. (The decryption key will probably be in plaintext in `trio/ci.sh`, since Github secrets don't get passed to CI runs on PRs from forks, but I think this is enough obscurity to avoid attracting unwanted attention.)
