### ISSUE TITLE
Mixin that automatically wraps methods with trio.to_thread.run_sync

### ISSUE THREAD

**Issue by kanwepr** [python-trio/trio#1674]
Is there something wrong with this mixin (or with the idea behind it):

```
class AsyncMixin:
    def __getattr__(self, name):
        prefix = "async_"
        if name.startswith(prefix):
            sync_fn = getattr(self, name[len(prefix) :])

            async def async_fn(*args, **kwargs):
                return await trio.to_thread.run_sync(functools.partial(sync_fn, *args, **kwargs))

            return async_fn
        else:
            return super().__getattr__(name)
```

I use it in Django querysets and models, and it has made my life so much easier that I'm wondering if I'm missing the catch.  (I'm new to trio.)

**Comment by parity3** [comment]
Some immediate things I can personally see:

- how do you guarantee that the caller is in a trio context / the trio thread? I suppose you could add logic to detect that and if not, it just assumes you're already in sync-land and executes the function bare? More overhead but I suppose it works in the name of convenience.. Lots of "magic" though.
- related to the first bullet: it'd be better that the caller just "know" that the function it is calling is non-async-ified in a more explicit sense, both for readability and debugging purposes
- there are cancellation semantics to worry about.. ie if the caller is putting this function in a move_on_after(), the sync function won't be interrupted by default; it'll just continue waiting; I could be wrong here.
- async_ may be a confusing prefix to apply to a wrapped function which is meant to run "sync" but in the thread pool. Perhaps a prefix like "sync_inthread" is more appropriate?
- you probably lose some valuable type hints this way if you are working with an IDE or mypy, etc.. but this may be avoidable, not sure
- libraries like sqlite database connections get real picky when switching around threads so you'd still have to worry about thread safety and policies, but that's just a caveat

**Comment by oremanj** [comment]
It seems reasonable, with the caveats that @parity3 mentioned, but I think it's probably too magical to make it into mainline Trio. That means we don't have a Trio action item from this issue, so I'll go ahead and close it.
