### ISSUE TITLE
receive_some on a ReceiveStream splits the header from content on a HTTP response ?

### ISSUE THREAD

**Issue by bitlogik** [python-trio/trio#1689]
Using trio 0.13.0.
I spent some time, because `await stream.receive_some()` only returns the HTTP header data.

```
stream = await trio.open_tcp_stream(backend_addr.hostname, backend_addr.port)
if backend_addr.use_ssl:
    ssl_context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    ssl_context.load_default_certs()
    stream = trio.SSLStream(stream, ssl_context, server_hostname=backend_addr.hostname)
req = b"GET %s HTTP/1.1\r\nHost: %s \r\n\r\n" % (target, backend_addr.hostname.encode("idna"))
await stream.send_all(req)
rep = await stream.receive_some()
rep2 = await stream.receive_some()
print(req.decode("utf8"))
print(rep.decode("utf8"))
print(rep2.decode("utf8"))
```

gives out :
```
> GET /redir/foo/bar?a=1&b=2 HTTP/1.1
Host: example.com

> HTTP/1.1 200 OK
content-type: text/html;charset=utf-8
content-length: 1071
date: Fri, 21 Aug 2020 13:48:19 GMT
server: mysrv

> <!doctype html>\n<html lang="en">\n\n<head>...</body>\n\n</html>

```

with `rep = await stream.receive_some(4096)`, this is the same result. trio behaves like it reads internally the stream and separates the header from the content and receive header and content in 2 chunks. It is normal or expected? Is it related to an underlying HTTP server mechanism? I seek for that, and I feel this is a trio related behavior.

**Comment by bitlogik** [comment]
We finally tracked down the root cause issue and changed it. There was indeed 3 stream.send_all : one for the headers, one for data (if any) and a final for EndOfMessage. The code was refactor so that it sends only one send_all with all the data of the page.
https://github.com/bitlogik/guardata/commit/bbc875998cab9ee19eda4b6f4888656638aa9f56#diff-a2646660dfbfbb60dd85423b35d23545

**Comment by pquentin** [comment]
@bitlogik Glad that you fixed your problem! However, the correct fix isn't to call `send_all` once, it's to call `receive_some` in a loop until you get the empty byte string `b""`, as documented in https://trio.readthedocs.io/en/stable/reference-io.html#trio.abc.ReceiveStream.receive_some
