### ISSUE TITLE
Windows pipe can't receive more than DEFAULT_RECEIVE_SIZE bytes

### ISSUE THREAD

**Issue by richardsheridan** [python-trio/trio#1773]
Still working on my multiprocessing wrapper. I thought I was "done" and began stress testing it. I found that I cannot send large objects over the named pipe.  I believe this is a minimal reproducible example:

```python
import trio
from trio._windows_pipes import PipeReceiveStream, PipeSendStream, DEFAULT_RECEIVE_SIZE
from multiprocessing import Process, Pipe


def echo(recv_pipe, send_pipe):
    bytes = recv_pipe.recv_bytes()
    print('received', flush=True)
    send_pipe.send_bytes(bytes)
    print('sent', flush=True)
    send_pipe.send_bytes(b"")


async def main():
    child_recv_pipe, parent_send_pipe = Pipe(duplex=False)
    parent_recv_pipe, child_send_pipe = Pipe(duplex=False)
    proc = Process(target=echo, args=(child_recv_pipe, child_send_pipe), daemon=True)
    proc.start()
    parent_send_stream = PipeSendStream(parent_send_pipe.fileno())
    parent_recv_stream = PipeReceiveStream(parent_recv_pipe.fileno())
    try:
        await parent_send_stream.send_all(bytearray(DEFAULT_RECEIVE_SIZE+10**6))
        async for response in parent_recv_stream:
            print(len(response))
    finally:
        parent_recv_stream._handle_holder.handle = -1
        parent_send_stream._handle_holder.handle = -1
    print("done", flush=True)


if __name__ == "__main__":
    trio.run(main)
```
This raises `OSError: [WinError 234] More data is available` in `parent_send_stream.receive_some()`.  ERROR_MORE_DATA is apparently [not an error despite the name](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile#pipes) and just indicates you should keep reading. I guess this should be special-cased in `wait_overlapped`:

https://github.com/python-trio/trio/blob/02933b7f07df20d3dbb550bbfe2e59b332cdec37/trio/_core/_io_windows.py#L732-L746

Could the fix be as simple as `elif code == ErrorCodes.ERROR_MORE_DATA: pass`? That fixes my test case. It might also be possible to use [PeekNamedPipe](https://docs.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-peeknamedpipe) at this point to provide a hint what the next receive size should be on this handle...

Alternatively I could try to set my pipe to `PIPE_READMODE_BYTE`, as multiprocessing uses message oriented pipes by default.

**Comment by njsmith** [comment]
`async for response in parent_recv_stream` is a shorthand for repeatedly calling `await parent_recv_stream.receive_some(DEFAULT_RECEIVE_SIZE)`, where the argument specifies the maximum amount of data to read. If you call `receive_some` directly, you can pass in a larger argument. Does that fix the issue for you?

(I suspect the long-term answer is that if/when we add explicit support for message-oriented windows named pipes, then that code will want to explicitly handle `ERROR_MORE_DATA`. Handling it in `wait_overlapped` seems too low-level to me.)

**Comment by richardsheridan** [comment]
Unfortunately, in the multiprocessing wrapper I won't generally know how big the response message is.

It looks like it's possible to catch the OSError in `receive_some`, since we don't need the `size` return value from `_core.readinto_overlapped`, even if invoking the exception machinery on every chunk be relatively inefficient. So I will make a custom `PipeReceiveStream` for myself for now with that change.

**Comment by njsmith** [comment]
Oh yeah, I guess my question was whether tweaking the argument could work in any case, because if not then there's no point in writing clever code to automatically tweak the argument :-)

But yeah, the solution is probably to write some loop like:

```python
CHUNK_SIZE = 65536

class PipeReceiveChannel(Channel):
    ...
    async def receive(self):
        message = bytearray()
        done = False
        while not done:
            chunk = bytearray(CHUNK_SIZE)
            try:
                await trio.lowlevel.readinto_overlapped(..., chunk)
            except OSError as exc:
                if exc.winerror == ERROR_MORE_DATA:
                    done = False
                else:
                    raise
            else:
                done = True
            message += chunk
       return message
```

**Comment by richardsheridan** [comment]
As you can see in #1782, `PeekNamedPipe` is really the way to go because any message length up to the system limit can be handled with just two calls to `readinto_overlapped`, and there's still a fast path for short messages.  So I think it is safe to call this "not a bug" but rather just failing to account for the differences between message-oriented and byte-oriented windows pipes.
