### ISSUE TITLE
Cancellation creates long-lived references to cyclic references to tasks and their local names

### ISSUE THREAD

**Issue by richardsheridan** [python-trio/trio#1793]
Almost certainly related to #1770, but different symptoms: an object whose lifetime should be confined to a scope lives on well after the async function returns.  This example on Win10 trio 0.17 changes depending on whether the cancellation occurs or not:

```python
import gc
import trio
import weakref


class A:
    pass


async def task():
    a = A()
    weakref.finalize(a, lambda: print("destroyed"))
    print("task start")
    with trio.CancelScope() as c:
        c.cancel()  # remove to destroy `a` as `task()` exits and decrements the refcount of `a` as expected
        await trio.sleep(0)
    print("task finished")


async def amain():
    await task()
    print("main finished")
    gc.collect()
    print("trio GC finished")


if __name__ == "__main__":
    trio.run(amain)
    print("trio finished")
    gc.collect()
    print("final GC finished")
```

Output if not cancelled (expected output in both cases):
```
task start
task finished
destroyed
main finished
trio GC finished
trio finished
final GC finished
```

Output if cancelled:
```
task start
task finished
main finished
trio GC finished
trio finished
destroyed
final GC finished
```
I probably wouldn't have noticed this, except that in my real application `a` is 600mb of numpy arrays that stack up to outrageous memory usage fairly quickly. Note that the gc is ineffective within trio in this case: in my app, the effectiveness of a within-trio GC is (so far) unpredictable.

**Comment by richardsheridan** [comment]
With a little help from objgraph we can see that the Cancelled object itself is participating in the reference cycle that is held together with a bunch of traceback objects.
![ref_cycle](https://user-images.githubusercontent.com/8000454/99191916-e269b980-273d-11eb-94fe-e2d9b904792a.png)

I guess this is not the first instance of traceback cycles keeping locals alive:

https://stackoverflow.com/questions/7375492/proper-care-and-safety-when-dealing-with-traceback-objects-from-sys-exc-info
https://bugs.python.org/issue1565525

Still not clear to me where exactly trio could break the cycle though

**Comment by asvetlov** [comment]
Sorry, I don't think the test is correct.

```
async def task():
    a = A()
    weakref.finalize(a, lambda: print("destroyed"))
    print("task start")
    with trio.CancelScope() as c:
        c.cancel()  # remove to destroy `a` as expected
        await trio.sleep(0)
    print("task finished")
```
Why on `c.cancel()` call the `a` instance should be destroyed?
The question is not specific to the trio but about the CPython rules in general.
Did you mean a different test case maybe?

**Comment by njsmith** [comment]
@asvetlov it's a bit confusing, but I think the idea is that *after `task` exits* the `a` should be destroyed immediately by the refcount collector. But somehow if there was a cancellation inside `task`, then `task`'s stack frame ends up in a reference cycle, so the presence or absence of the `c.cancel()` line changes when `a` ends up being destroyed.

**Comment by richardsheridan** [comment]
I think @njsmith has the right interpretation, hopefully my edit to the test case comment makes this a bit more clear.

**Comment by njsmith** [comment]
Having diagnosed #1770 now (see https://github.com/python-trio/trio/pull/1805 and https://github.com/python-trio/outcome/pull/29), I think this is in fact a dupe, so I'm going to close it until we find evidence otherwise. (Note that in #1770, the example involves calling `trio.sleep`, which uses a cancel scope internally.)
