### ISSUE TITLE
Add note to Condition docs suggesting possible use of ParkingLot

### ISSUE THREAD

**Issue by JamesOldfield** [python-trio/trio#1822]
OK, so I wrote a long ramble (copied below for posterity!) about how the interface of `Condition` could be improved, which I planned to post here with the title "Consider allowing `Condition.notify()` without acquiring the lock". In the end, especially after reading through #1082, I realised I could (/should) just have been using `ParkingLot` directly, which does precisely what I need it to do. Compare this snippet with condition variable and semaphore versions below:

    async def do_wait(parking_lot, buffer):
        while not buffer:
            await parking_lot.park()
        buffer_copy = buffer[:]
        del buffer[:]
        return buffer_copy
        
    def do_put(parking_lot, buffer, more_data):
        buffer.extend(more_data)
        parking_lot.unpark()

I didn't find this originally mainly because I just didn't even know that `ParkingLot` existed (I actually found it by looking in the source code of `trio.Condition` rather than looking in the docs!). Partly this was because I was using an old version of trio (I've now updated), where that part of the library was still called `hazmat` rather than `lowlevel`, so I never thought to look there - I just looked through [synchronisation primatives](https://trio.readthedocs.io/en/stable/reference-core.html#lower-level-synchronization-primitives) and found the one most like what I would have used in multithreaded code. (To be honest I missed [`Event`](https://trio.readthedocs.io/en/stable/reference-core.html#broadcasting-an-event-with-event) too, although it doesn't appear to quite be what I want because `wait()` doesn't reset it.)

So now I'd like to phrase my issue as: Please consider adding an info box to the documentation of `trio.Condition` suggesting that often using `lowlevel.ParkingLot` directly may be simpler than using `Condition`. It's worth noting that parts of its interface are extremely analogous to condition variables (`wait()` -> `park()`, `notify()` -> `unpark()`, `notify_all()` -> `unpark_all()`). It would maybe be worth pointing to `Event` too, even though that's on the same page. You could maybe mention the situation(s) in which you actually might want to use a full-blown `Condition`, although I'm not sure what those are.

## Original ramble (feel free to ignore!)

In Python's threading module, a `Condition` object's associated `Lock` must be locked before calling `notify()` or `notify_all()`:

    def do_wait(condition, buffer):
        with condition:
            while not buffer:
                condition.wait()
            buffer_copy = buffer[:]
            del buffer[:]
        return buffer_copy
    
    def do_put(condition, buffer, more_data):
        with condition:
            buffer.extend(more_data)
        condition.notify()  # <-- Error! Lock not held

This is different from e.g. the C++ standard library API, where there's no requirement that the associated `std::mutex` be locked when a `std::condition_variable` is notified. In fact it's preferable for the mutex to be unlocked first so that when the waiting thread is woken it can immediately acquire the mutex rather than being sent straight back to sleep.

I'm not 100% of the reason behind this API decision. Perhaps the idea is to prevent the developer mistake of forgetting to lock the mutex altogether in `do_put()`. But maybe a bigger reason is that I suspect Python actually takes advantage of the lock being acquired to do non-trivial things in the notification, like notifying precisely the right number of waiters (in case at least `n` are queued) and notifying them in the order they waited (in case there are strictly more than `n` queued).

For Trio, I don't think these concerns apply, because you could consider that there is a global "lock" aquired during the call to `notify()` in the sense that it can't be preempted by another task. Even the user code (like `buffer.extend(more_data)` above) doesn't need to acquire a lock so long as it's careful not to put a checkpoint in the middle. But requiring the variable to be locked prevents the use of a `Condition` to signal from non-async code (called indirectly from async code e.g. a callback) to async code, which seems to be an ideal use of `trio.Condition`:

    def do_put(condition, buffer, more_data):
        buffer.extend(more_data)
        async with condition:  # <-- Error! async with in non-async fn
            condition.notify()

Now that I think about it, I don't even see a reason why the lock needs to be acquired for `wait()`. It doesn't make such a difference because you have to be in async code to call `wait()` anyway... But maybe the lock part of the condition variable is just redundant for async code?

As a footnote, the easiest alternative I've found for this use case is a `Semaphore`, but I find it a bit more confusing:

    async def do_wait(semaphore, buffer):
        while not buffer:
            await semaphore.acquire()
        buffer_copy = buffer[:]
        del buffer[:]
        return buffer_copy
        
    def do_put(semaphore, buffer, more_data):
        buffer.extend(more_data)
        if semaphore.value == 0:
            semaphore.release()

**Comment by JamesOldfield** [comment]
I'm closing this issue now. It's been open long enough to get a bit of visibility, and if anything it's a dupe of the issue I linked to above anyway.

**Comment by pquentin** [comment]
I read it when you opened it, and it was very interesting: thank you for this!
