### ISSUE TITLE
Clarify which functions can be called from non-trio threads

### ISSUE THREAD

**Issue by Nikratio** [python-trio/trio#1839]
It would be great if the documentation could clarify which Trio functions may be called only from a Trio thread, and which ones may be called from other threads as well. I think the best place for this kind of information would be the [Threads (if you must)](https://trio.readthedocs.io/en/stable/reference-core.html#trio.from_thread.run) section.

In my particular case, I am wondering if I need to wrap a call to `trio.lowlevel.notify_closing` into `trio.from_thread.run_sync` or not.

I suspect the answer is "all trio.* functions should only be called from the Trio thread unless they are documented otherwise", but it would be great to make this explicit.

**Comment by oremanj** [comment]
I think we already have this at https://trio.readthedocs.io/en/stable/reference-core.html#thread-safety:

> The vast majority of Trio’s API is not thread safe: it can only be used from inside a call to trio.run(). This manual doesn’t bother documenting this on individual calls; unless specifically noted otherwise, you should assume that it isn’t safe to call any Trio functions from anywhere except the Trio thread. (But see below if you really do need to work with threads.)

Yes, you should wrap in `trio.from_thread.run_sync()` any call to `notify_closing()` that happens from a thread other than the Trio thread.
