### ISSUE TITLE
Clarify that the deadline in `trio.sleep_until` is according to `trio.current_time()`

### ISSUE THREAD

**Issue by cubranic** [python-trio/trio#1860]
From the [docs](https://trio.readthedocs.io/en/stable/reference-core.html#trio.sleep_until):
> Pause execution of the current task until the given time.
> 
> The difference between `sleep()` and `sleep_until()` is that the former takes a relative time and the latter takes an absolute time.

I take it from the intro to the "Time and Clocks" section that this deadline is not according to any computer clock, but Trio's own internal one? If so, it might be useful to say that more explicitly in the function docstring. (I'm happy to contribute a PR once you confirm this is the case.)

**Comment by pquentin** [comment]
> I take it from the intro to the "Time and Clocks" section that this deadline is not according to any computer clock, but Trio's own internal one?

Yes, that's right. Maybe writing "... absolute time according to Trio's internal clock" is enough?
