### ISSUE TITLE
Teach github that our generated files are generated

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#1966]
Apparently this is a thing you can do: https://docs.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github

I'm thinking of the files generated by `trio/_tools/gen_exports.py`.

**Comment by pquentin** [comment]
Neat! We can also use .gitattributes to teach git (and possibly GitHub?) to ignore commits where we ran yapf or black all over the code base

**Comment by dhirschfeld** [comment]
> *We can also use `.gitattributes` to teach git (and possibly GitHub?) to ignore commits where we ran yapf or black all over the code base*

***xref:*** https://github.com/psf/black/pull/1419

**Comment by pquentin** [comment]
Ah right, it's another file, thanks for the reference!
