### ISSUE TITLE
add a copyright notice and actually apply the apache 2 licence

### ISSUE THREAD

**Issue by graingert** [python-trio/trio#1972]
the licence text refers to an "above copyright notice", but no notice is present: https://github.com/python-trio/trio/blob/master/LICENSE.MIT#L11

the apache licence text is also present but hasn't been applied, application instruction here https://github.com/python-trio/trio/blob/master/LICENSE.APACHE2#L179-L202

**Comment by njsmith** [comment]
Is this causing a practical problem for you? I did go deep down the rabbit hole on this at some point, and AFAICT copyright statements are a huge mess -- they have no particular legal weight, but *removing* them can create legal liability, so you can never remove them regardless of whether they're accurate or not. Plus our licensing status seems unambiguous enough, and we're within the range of what projects commonly do, and it doesn't seem to cause problems. So my instinct is to leave things be until someone has a specific issue (e.g. "Our compliance team says we can't use trio unless you add a certain copyright statement").

**Comment by graingert** [comment]
I need to comply with the terms on the MIT licence and it makes a demand I cannot comply with

**Comment by njsmith** [comment]
Somewhat authoritative-looking post from the Linux Foundation with advice on copyright notices: https://www.linuxfoundation.org/en/blog/copyright-notices-in-open-source-software-projects/

**Comment by graingert** [comment]
Seems like you want "Copyright Contributors to the Trio project."

**Comment by graingert** [comment]
@njsmith there's a licence I saw that cPython use for doc snippets that doesn't require a copyright declaration: https://opensource.org/licenses/0BSD

**Comment by njsmith** [comment]
If you really want to add `Copyright Contributors to the Trio project` or similar to `LICENSE.MIT`, then I guess go for it.
