### ISSUE TITLE
set up a welcoming bot

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#201]
For trio, I'm trying out the super-welcoming model of maintainership, where we turn on branch protection and then automatically invite everyone who meets some minimum objective standard – submitting one good pull request – to join the team, if they want.

Currently, this is done manually: after merging someone's first pull request, I have to remember to type in a comment asking if they'd like to join the organization. This is annoying, error prone, can create some sort of social pressure because it's a real person asking, and may leave the impression that there's still some judgement call being made, all of which undermines the goal.

Instead, what I'd like to have is a bot that notices when someone's first pull request is merged, and automatically posts a comment welcoming them and explaining the system, and then sends them a collaborator invitation.

I don't know anything about writing GitHub bots, but some friends-of-trio like @brettcannon and @carreau do, so maybe we can get some tips from them.

**Comment by Carreau** [comment]
Rust uses [highfive](https://github.com/servo/highfive) for new contributors in particular. Usually my bots are stateless.

Hopefully we can soon write a bot that uses trio and gidgethub to welcome new contributors and give them commit access. it should not be too hard.

**Comment by njsmith** [comment]
I'd also perfectly happy with a bot that uses gidgethub but not trio. I'm not that dogmatic :-)

I assume that the state you're worried about is tracking whether this the first PR from the given contributor? I guess that isn't entirely trivial – I was going to say that github tracks it to put that "first time contributor!" label on the PR, but that seems to disappear after the PR is merged, and I don't know if it's accessible from the API anyway... but yeah, maintaining a set of accounts-already-invited on disk shouldn't be *too* hard, using sqlite or whatever.

**Comment by Carreau** [comment]
> I'd also perfectly happy with a bot that uses gidgethub but not trio. I'm not that dogmatic :-)

I know, I was (half) joking. Though It __would__ be nice.

> I assume that the state you're worried about is tracking whether this the first PR from the given contributor? I guess that isn't entirely trivial – I was going to say that github tracks it to put that "first time contributor!" label on the PR, but that seems to disappear after the PR is merged, and I don't know if it's accessible from the API anyway... but yeah, maintaining a set of accounts-already-invited on disk shouldn't be too hard, using sqlite or whatever.

Yes, there is also the question of repo vs org. It's doable in both case.

**Comment by brettcannon** [comment]
I'm unaware of the API exposing the "first-time contributor" banner thing they put on for people's first PR.

**Comment by njsmith** [comment]
Matthias makes a good point anyway that we actually want "first-time contributor anywhere in the org", while the banner (or doing a search of pull requests, or similar) would be per-repo. So maintaining some state is probably the way to go.

**Comment by kyrias** [comment]
Would essentially just need to set up a a PR webhook and then:

* Unless action:closed/merged:true
* check if member is already on org member list, if not
* (check if user is listed on some kind of blacklist, if not)? Might be good to have as a feature just in case.
* try to add the user as a member to the org

**Comment by njsmith** [comment]
I think we want to keep track of who we've sent invitations to, and make sure to only invite any given person once. The case I'm worried about is where someone has decided they don't want to join the team, and declines the invitation; we shouldn't keep spamming them after that. Consent is important!

**Comment by kyrias** [comment]
True, though that would just be the same list as the "blacklist", and just append everyone to that.

**Comment by njsmith** [comment]
https://probot.github.io/apps/welcome/
https://probot.github.io/apps/invite-contributors/

**Comment by oremanj** [comment]
trio-bot now exists, thanks @njsmith!
