### ISSUE TITLE
Implement a better MultiError exception printer on IPython

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#205]
Right now, trio has some code (in `trio/_core/_multierror.py`) to detect when it's running under IPython, and if so then it tries to register a special error printer for `MultiError` exceptions.

Currently, it's a bit lazy though: it just reuses our usual `sys.excepthook` printer, which gives something that looks like a normal python traceback, not the fancy-shiny traceback that IPython users are accustomed to. This isn't urgent, but at some point it would be good to rewrite this to use IPython's fancy exception printing machinery.

(There is also an annoying limitation in the current IPython exception printing hook API, which is that there can only be one hook installed at a time. Ideally we should be able to install our hook without colliding with anyone else who might also be trying to use this hook. But this will need changes to IPython upstream.)

CC: @Carreau

**Comment by Carreau** [comment]
I've been meaning to refactor extracting the tracebacks tools of IPython I can also try to pull it as a seprate package that does not depends on IPython. 
https://github.com/Qix-/better-exceptions might also be a thing to look at.

**Comment by Zac-HD** [comment]
Closing this because `MultiError.catch()` is deprecated in favor of `exceptiongroup.catch()` (or `except*`, on Python 3.11).

Per https://github.com/ipython/ipython/issues/13753 there are still some rough edges, but since #2213 that's not really Trio's problem.
