### ISSUE TITLE
Proposal: Consider making many CI checks non-required

### ISSUE THREAD

**Issue by Fuyukai** [python-trio/trio#2207]
This comes off the back of an issue where the CI wasn't passing due to multiple upstream bugs, blocking *everything*, even completely unrelated pull requests (even though the tests themselves were sound). This has been a recurring problem, with flaky tests blocking PRs for years now. Should these tests be fixed? Probably. But it's not our responsibility to work around upstream bugs.

This also means the CI matrix can't be updated, as removing any required checks means the PR can't be merged without someone with the permission to override it.

My proposal:

 - ``-dev`` or ``nightly`` versions should not be required checks. Upstream breaking is **not** our problem, unless it's a deprecation (but warnings should catch that!). 
 - Soon-to-be-EOL versions should not be required checks. There's not much point maintaining compatibility with a version that will be EOL by the next release of Trio.
 
I believe this strikes a good balance between correctness and "somebody else broke things".

**Comment by jakkdl** [comment]
randomly found this issue, this is currently implemented in the CI afaict.
