### ISSUE TITLE
Question: how the global 'current_time' appeared?

### ISSUE THREAD

**Issue by asvetlov** [python-trio/trio#2252]
I'm learning trio source base.
This [line](https://github.com/python-trio/trio/blob/master/trio/_core/_run.py#L443) I cannot understand.
```
        if current_time() >= self._deadline:
            self.cancel()
```
`current_time()` name is not imported at the module level.
It is not a local variable.
What magic adds to observable python namespaces?

**Comment by oremanj** [comment]
It is imported at the module level: `from ._generated_run import *` at the bottom of that file.

**Comment by asvetlov** [comment]
Thanks!
