### ISSUE TITLE
how to get the client address in trio

### ISSUE THREAD

**Issue by sbigtree** [python-trio/trio#2294]
For example
`client, address = socket.accept()`
but i do not  konw how to get the client address in trio

**Comment by pquentin** [comment]
If you're using the low level [`trio.socket`](https://trio.readthedocs.io/en/stable/reference-io.html#low-level-networking-with-trio-socket) then everything works as with the standard socket module, except it's async. For the higher-level APIs you can't access this information yet: https://github.com/python-trio/trio/issues/280
