### ISSUE TITLE
Data passed to child as parameter to fill returns empty

### ISSUE THREAD

**Issue by chang-zhao** [python-trio/trio#2329]
When a child fills a dictionary passed as the parameter, it returns from the nursery empty:

```
# The child
async def redis_pages(pages):
    pages = await redio.hgetall('pages').autodecode
    print(len(pages))
    # Prints the correct amount, so `pages` is a filled dict now 

# The parent (I'm using Quart-Trio):
@app.route('/<path:path>')
async def getting(path=''):
    pages = {}
    async with trio.open_nursery() as nursery:
        nursery.start_soon(redis_pages, pages)

        # some other stuff here, including:
        # nursery.start_soon(trio.to_thread.run_sync, ...)

    print(pages)
    # Prints an empty dict: "{}"
```
Linux 5.10, Python 3.10.4, Trio 0.20.0, Quart 0.17.0, Quart-Trio 0.9.1

I'm new to Python and especially Trio,  so excuse me if I did something wrong and it's not a bug.

**Comment by smurfix** [comment]
You're replacing the whole `pages` dictionary in the child. Instead you need to call `pages.update(await redio.hgetall('pages').autodecode)`.

This is not a Trio problem.
