### ISSUE TITLE
Python3.11 comes with ExceptionGroups and TaskGroups !

### ISSUE THREAD

**Issue by AmirHmZz** [python-trio/trio#2357]
What are benefits of using `Trio` in comparison with _Python3.11_ since `asyncio` now supports [ExceptionGroups](https://peps.python.org/pep-0654/) and TaskGroups?

**Comment by smurfix** [comment]
Taskgroups are still a bolt-on to asyncio and there are several cases where they are ignored rather thoroughly. `create_server` is one example. Also, there's the arcane Protocol+Transport construct which Trio has replaced with a reasonable and much more accessible Stream concept, which asyncio also has acquired but seems to have no plans to migrate to.

In any case this is not a problem with Trio, strictly speaking. We do have a forum for this kind of questions however. (And a Gitter chatroom.) https://trio.discourse.group/ https://gitter.im/python-trio/general Thus please excuse me closing this issue.
