### ISSUE TITLE
Do you plan to http client?

### ISSUE THREAD

**Issue by wku** [python-trio/trio#236]

**Comment by Carreau** [comment]
If I understand the question correctly the response is (as far as I can tell) : you need to use https://github.com/njsmith/h11 or https://github.com/python-hyper/hyper-h2 depending on wether you want to speak http 1.1 or 2.0. h11 and h2 are sans-io implementation of the protocol, so you can use them with trio/curio/asyncio/choose-you-async-framework. I would look at https://github.com/python-trio/trio/issues/105 as it is stated here there are sill some work to do to support TLS before starting working on an http client.

**Comment by njsmith** [comment]
Building your own client out of h11 or h2 is not easy... they take care of the low-level bits of the HTTP protocol, but there's a lot more on top that a good client has to worry about.

We don't plan to ship a http client as a built-in feature in the `trio` package, but we certainly do plan to have external packages that trio programs can use to make http requests. One possibility would be to add trio support to [asks](https://asks.readthedocs.io/en/latest/).

TLS support was implemented in #107, so it's available in current trio master and will be available in trio version 0.2, when I get around to releasing that...

**Comment by njsmith** [comment]
Closing this issue because I think it's answered, but if I'm wrong feel free to re-open.

**Comment by merrellb** [comment]
Earlier you suggested that urllib3 might be the best path to asynchronous http (https://github.com/python-trio/trio/issues/105).  I am unfamiliar with _asks_ but is it looking like a better path forward?  I've also put in an issue with urllib3 trying to get a sense of where things stand (https://github.com/shazow/urllib3/issues/1228) regarding trio.

I do think this issue may warrant a mention in the documentation (I almost created third issue before finding the other two).  I realize trio is aimed at a lower level functionality but HTTP requests are likely the first thing a lot of folks will want to do with trio and your fame with h11 may lead to expectations that there is a clear way to tie them together :-)  Even if there is no clear answer yet, a brief mention may reduce the number of extraneous issues raised.

**Comment by njsmith** [comment]
Basically :my impression is that `asks` is a plausible short-term solution (it exists, they're explicitly interested in trio support, could probably make it happen today (though it would need to depend on unreleased trio for ssl and async file support)), but in the long-term I'm dubious – there's a *ton* of fiddly details involved in implementing an async HTTP client, and it'd be much better to piggy-back on the excellent urllib3/requests maintainers instead of trying to reinvent all that.
