### ISSUE TITLE
Is it planned, in the near future, HTTP support in the core?

### ISSUE THREAD

**Issue by wku** [python-trio/trio#238]

**Comment by njsmith** [comment]
I feel like we already answered this in #236... If you have a different question can you elaborate?

**Comment by wku** [comment]
Thanks, ok

**Comment by njsmith** [comment]
...not sure if I'm missing something here. I guess I'll close it, but please do ask if you have a question that's not been answered :-). (You can click the "reopen" button, it's fine!)
