### ISSUE TITLE
Poetry compatibility with Trio

### ISSUE THREAD

**Issue by evanrittenhouse** [python-trio/trio#2394]
How would people feel about a `tools.poetry` section being added to `pyproject.toml`? I am happy to do it and at least get the dependencies loaded in. Might be an easier way to get new contributors up to speed. Given Poetry's widespread adoption, and Trio's focus on using the latest tools, I feel that this fits Trio's mission in both execution and theory.

**Comment by apollo13** [comment]
While poetry is used quite a bit I'd personally prefer something that uses https://peps.python.org/pep-0621/ to prevent further fracturing of the community. Github & others all have a hard time parsing the various file formats ;)

**Comment by Zac-HD** [comment]
I think we'd prefer to stick with packaging tools that follow the various standards in order to be as widely usable as possible.
