### ISSUE TITLE
Except hook incompatibility with exceptiongroup backport

### ISSUE THREAD

**Issue by vxgmichel** [python-trio/trio#2427]
Since version 6.54.0, hypothesis uses exception notes (PEP 678) to show falsifying examples underneath the raised exception. With python < 3.11, this is done using a custom exception hook provided by [exceptiongroup](https://github.com/agronholm/exceptiongroup), a backport of PEP 654. The problem is that trio also uses a custom excepthook to manage multi-errors. In practice, this leads to the falsifying example not being displayed depending on the import order. Even worse, simply having `pytest-trio` installed causes the falsifying examples to disappear. Consider the following test:
```python

from hypothesis import given
from hypothesis import strategies as st

@given(x=st.integers())
def test_notes(x):
    1/x
```
Without `pytest-trio` installed you would get:
```python
    @given(x=st.integers())
    def test_notes(x):
>       1/x
E       ZeroDivisionError: division by zero
E       Falsifying example: test_notes(
E           x=0,
E       )

test_notes.py:7: ZeroDivisionError
```
And with `pytest-trio` installed:
```python
    @given(x=st.integers())
    def test_notes(x):
>       1/x
E       ZeroDivisionError: division by zero

test_notes.py:7: ZeroDivisionError
```

**Comment by pquentin** [comment]
@agronholm Do you think #2217 would help here?

**Comment by agronholm** [comment]
Yup, since trio would no longer install its own hook. If you can manage to import `exceptiongroup` first, that would also work around this issue.

**Comment by pquentin** [comment]
Thanks I edited the description of #2213 so that it closes this issue when merged. A Trio release will quickly follow anyway, as it's a long awaited feature and Python 3.11 will be release next month.
