### ISSUE TITLE
`import trio` produces AttributeError with `attrs` version 19.2.0

### ISSUE THREAD

**Issue by peterzahemszky** [python-trio/trio#2439]
After having installed the **attrs** package (version 19.2.0) and **trio** (version 0.22.0) in a new virtual environment, I get the following error upon importing trio:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pz/playground/lib/python3.10/site-packages/trio/__init__.py", line 76, in <module>
    from ._dtls import DTLSEndpoint, DTLSChannel
  File "/home/pz/playground/lib/python3.10/site-packages/trio/_dtls.py", line 136, in <module>
    @attr.frozen
AttributeError: module 'attr' has no attribute 'frozen'
```

According to [setup.py](https://github.com/python-trio/trio/blob/master/setup.py#L82) this version of attrs should be supported. However, the `attr.frozen` object was only [introduced](https://www.attrs.org/en/stable/changelog.html#id87) in attrs version 20.1.0.

The issue disappears when I upgrade attrs to version 22.1.0.

**Comment by pquentin** [comment]
Thank you for noticing this. Would you be interested in updating setup.py to reflect this constraint?
