### ISSUE TITLE
Apport ExeptHook detection stopped working.

### ISSUE THREAD

**Issue by Xyaren** [python-trio/trio#2464]
The detection via the name `apport_excepthook` introduced in #1065,#1528 stopped working for me. 
Checking my system it seems apport has changed the name:
```
>>> import sys
>>> sys.excepthook.__name__
'partial_apport_excepthook'
```

Relevant change: https://github.com/canonical/apport/commit/ad6d801d264e9a7430d8d655fd04284a8871d68a#diff-262abd69bbc20e14d09d4b9041c97e2586e3f3f3db59acf4389b2485abe6dd7cR233

I suggest adding both names to the detection.

This started after updating from Ubuntu 22.04 to Ubuntu 22.10.

Thanks! 

Paging @pquentin, as you are the original Author of the workaround.

**Comment by A5rocks** [comment]
Hi, it looks like Ubuntu 23.10 and Ubuntu 23.04 (at least the Docker image for those) doesn't do this anymore. Unfortunately the Docker image for 22.10 doesn't work :( (as in `apt update` doesn't have valid ips)

Am I missing something or is this just a 22.10 thing?
