### ISSUE TITLE
Incorrect version in trio/_version.py on v0.22.0 tag

### ISSUE THREAD

**Issue by mgorny** [python-trio/trio#2485]
When checking out trio from the `v0.22.0` tag, https://github.com/python-trio/trio/blob/v0.22.0/trio/_version.py incorrectly states the version as:

```
__version__ = "0.21.0+dev"
```

Noticed this because we use GitHub archives for packaging on Gentoo, and trio ended up being installed as `0.21.0+dev`, therefore breaking version constraints in other packages.

**Comment by pquentin** [comment]
Ouch, sorry about that. I'll make an emergency v0.22.1 release.

**Comment by mgorny** [comment]
Well, it's not a big deal for us (I've just `sed`-ed it) but I don't know if anybody else's impacted.
