### ISSUE TITLE
what's the roadmap of this project?  can i use it for now?

### ISSUE THREAD

**Issue by notedit** [python-trio/trio#255]

**Comment by njsmith** [comment]
Yes, you can use it now. It's young, there are a few things missing, and you should read what it says in issue #1 and be prepared for a certain amount of change as we dial in on the best APIs, but everything that does exist is carefully tested and fully documented, so you can at least see what you're getting. Whether this makes it appropriate for your project is something only you can answer :-). But we're very interested in having people try it out and give feedback.

As a volunteer run project, it's hard to have a formal roadmap. I'm actually not sure what you're hoping for -- what kind of roadmap would be useful?

**Comment by notedit** [comment]
we use python3 a lot,  but the asyncio's api is not so good to use.   trio looks promising and i like the design.  i hope trio have a stable api and does not have serious bug.  i want to try it in my projcet.

**Comment by njsmith** [comment]
I also hope trio has a stable API and no serious bugs :-). I am trying to make it stable as quickly as possible, but I won't make any promises until after we have some more experience using it in real applications.

**Comment by notedit** [comment]
i will try trio in my private project and keep an eye on this.   thanks for your working. just close this.

**Comment by njsmith** [comment]
Good luck!
