### ISSUE TITLE
add "path.walk" or "path.listdir"

### ISSUE THREAD

**Issue by xianyongjian080402** [python-trio/trio#2578]
I want to do the folder traversal operation, but aiofiles doesn't seem to support it

I suggest adding this

(Can you help me?)

**Comment by A5rocks** [comment]
I think `trio.Path.iterdir` does that, based on the docs: https://trio.readthedocs.io/en/stable/reference-io.html#trio.Path.iterdir

Is there something I'm missing?

**Comment by xianyongjian080402** [comment]
Uh-oh, sorry, I didn't see that

thank you!
