### ISSUE TITLE
Is it possible to make codecov action not "fail" until all other runs are completed?

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2689]
As I'm currently juggling several PRs and since the added xfail's on 3.12 it's not possible to see the :heavy_check_mark: vs :x: on a PR to see at a glance if it passes test. But, as soon as the first result is pushed to codecov it will fail and display :x:, until however longer time later when enough results have come in that it passes. I'd personally much prefer if it was possible to mark it as not giving a result until all results are in, so I can rely on the status icon of :heavy_check_mark: vs :x: vs :yellow_circle:.

One solution would be:
> One thought I have on this, though, is that what Hynek advocates for in his article https://hynek.me/articles/ditch-codecov-python/ could be useful here too. Maybe, if we merged all the reports on the GHA side and made just a single upload to Codecov, it could help with the rate limit just enough for this CI to have the best of two worlds: stability + ability to view coverage on Codecov's web UI.

as mentioned in https://github.com/python-trio/trio/pull/2672#pullrequestreview-1498778904

**Comment by jakkdl** [comment]
oh, and somewhat related - I'm getting duplicate codecov checks, e.g. in https://github.com/python-trio/trio/pull/2686

**Comment by jakkdl** [comment]
Gonna bump this after codecov flakiness in https://github.com/python-trio/trio/pull/2812#issuecomment-1763328467

**Comment by richardsheridan** [comment]
I implemented something inspired by Hynek's post in my repo fwiw: https://github.com/richardsheridan/trio-parallel/pull/114
