### ISSUE TITLE
RFE: please start making github rleases

### ISSUE THREAD

**Issue by kloczek** [python-trio/trio#2695]
Is it possible next time on release new version make the github release to have entry on https://github.com/python-trio/trio/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

**Comment by A5rocks** [comment]
Hi! This sounds alright, though I haven't actually seen too many GitHub releases so I'm not sure what's in them. What do you expect in a release? (i.e. changelog? new contributors? ...)

I'm surprised GitHub doesn't notify people on new tags existing given those show up under the releases heading on the repository homepage!

**Comment by kloczek** [comment]
In simplest scenario can be empty text 😄 (many maintainers actually i not adding any comments).

If you want add any comment about release (high level description of the changes in new release) all that is your decision.

**Comment by A5rocks** [comment]
I've made https://github.com/python-trio/trio/releases/tag/v0.22.2 for the latest patch release. I am keeping this open until I write what to do down in the documentation for releasing!

**Comment by kloczek** [comment]
Thank you 👍

**Comment by kloczek** [comment]
Thank you 👍
