### ISSUE TITLE
Run black+isort on code generated by `gen_exports.py`

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2750]
See https://github.com/python-trio/trio/pull/2733#discussion_r1289625533 and https://github.com/python-trio/trio/pull/2743#discussion_r1285299714 and https://github.com/python-trio/trio/pull/2743#discussion_r1285266764

Should maybe also report issues that aren't just waiting for release upstream to https://github.com/berkerpeksag/astor

**Comment by TeamSpen210** [comment]
Would be a nice tidyup, especially since `isort` should collapse multiple imports, so you can get rid of the basic check I did to prevent those. To maximise cross-platformness, might be best to call them via `subprocess.run([sys.executable, "-m", ...])` so we don't require `python` or the executable to be on `PATH`.

**Comment by jakkdl** [comment]
Both of them look to have an API, so we shouldn't need to involve external processes at all

**Comment by Zac-HD** [comment]
You might want to use [`shed`](https://github.com/Zac-HD/shed)?  It includes Black and Isort, ensures that the results are idempotent, does some further cleanups, and the Python API is easier to use than those of the wrapped tools.

**Comment by jakkdl** [comment]
> It'd make more sense to use `shed` on the whole repo - if we just used it here, we might end up in a situation where it produces different results to running black/isort standalone.

I was about to make that comment, but even if it does produce slightly different code the problem would only happen if `shed` output code that doesn't pass black/isort. That in general shouldn't happen - but `shed` ignores project configs iirc, which *could* cause a diff if we were to turn on `--preview` for black, or modify isort settings.

**Comment by A5rocks** [comment]
I think this is completed now?
