### ISSUE TITLE
Support task priority in `trio.CapacityLimiter()` (and `ParkingLot`)

### ISSUE THREAD

**Issue by Zac-HD** [python-trio/trio#2758]
## Motivation

Application-level task priority is a generally useful thing to have available!  To give a concrete example:

I often have some large stream of many thousand jobs I'd like to run, each comprising an unknown number (typically 1--1000) of async tasks - so the tree is very wide at the top level, and relatively deep in each subtree.  Each job needs to hold a moderately expensive resource for the entire lifetime, but we can only run ~100 subtasks at any given time.  Our performance goal is to saturate throughput of subtasks, using fewer concurrent jobs where reasonably practical - it's not worth estimating job size or reordering jobs in the stream.

We therefore want to use a `CapacityLimiter` for the subtasks, and prioritize those associated with the earliest jobs (i.e. the started jobs with the fewest remaining subtasks).  However, `CapacityLimiter` doesn't have any priority mechanism yet!

We can work around that by using a `CapacityLimiter` for the higher-level jobs too, which keeps everything within resource limits - at the cost of both under-saturating subtask throughput at times, and holding resources open for more simultaneous jobs than are actually required.  Getting fancy by dynamically adjusting the total_tokens for the job-level capacity limiter can actually make this pretty efficient if you're careful, but... a real priority system would be much easier to work with.

## Proposed API

`CapacityLimiter.acquire[_on_behalf_of][_nowait]()` takes a new optional argument, `priority=...`.  Once you've acquired a token either with or without a priority, attempting to do so respectively without or with is an error.  Priorities must be hashable and comparable.  `CapacityLimiter.__aenter__` remains non-prioritized, but we add three new context-manager methods:  `.priority(value, /)` for manual control, and `.depth_first()` or `.breadth_first()` as convenience methods.

`ParkingLot.park()` adds a new `priority=` argument, and `.unpark()` always unparks in descending order by priority (breaking ties by age in queue, i.e. the status quo when priority does not override).  

For performance reasons we might need a new `PriorityParkingLot` class, but for `CapacityLimiter` I'd rather stick to a single type with a new optional feature - I think this will be less complicated for users than splitting out a `PrioritizedCapacityLimiter` or whatever we'd call it.

## Implementation
<details>
<summary>fiddly and in places annoying, but entirely feasible</summary>

#### in `CapacityLimiter()` objects
The priority-related complexity lives in the embedded `ParkingLot`, meaning that we only need to pass priorities through `acquire[_on_behalf_of][_nowait]()` and define the new context manager methods.  The `.depth_first()` or `.breadth_first()` methods use a priority key computed from the position of the current task's nursery in the tree of all nurseries in this run - tasks in the same nursery (`Task.eventual_parent_nursery` for startable tasks, or `.parent_nursery` otherwise) have equal priority.

#### stable ordering for nurseries
Because the nurseries in some run always form a tree, we can identify each nursery by creation order (0, 1, 2, etc.), and "address" any nursery by the sequence of its ancestors' IDs.  These addresses are stable, cheap to assign as an attribute on nursery creation, cheap to access, and easy to transform into breadth-first or depth-first ordering keys.

#### in `ParkingLot` objects
Changes here are motivated by necessity for `CapacityLimiter`, but also seem independently useful.  I think that a conversion to priority-aware `ParkingLot` is fairly straightforward by switching `_parked: OrderedDict[Task, None]` to `SortedSet[tuple[priority, Task]]` - my impression is that the uniqueness of `OrderedDict` elements is enforced elsewhere and coincidentally upheld by using a dict with tasks as keys, rather than a property we need to enforce (i.e. by using a `SortedSet[Task]` with `key: dict[Task, priority].get`).

In principle we could switch over to _always_ using priorities in `ParkingLot`, with the default constant-`0` priority matching the current behavior.  In practice I think the performance cost (e.g. ~log-n instead of constant-time pops) might be unacceptable in such a critical piece of code, in which case we'd need to implement a whole almost-identical `PriorityParkingLot`.  This feels annoying, but not too painful since the code in question doesn't change much.

</details>

## Notes

- I'm personally pretty keen to use `with limiter.depth_first():` in my motivating cases above!
- This issue proposes some pretty wide-spread changes for a relatively narrow motivation.  I think it's still worth taking the wider principled approach here, but also plausible that we decide it's not worth it, or that we should get some downstream experience before adding this to Trio (which would in fact be possible)
- I'm not especially attached to any of the names or interfaces proposed here, but thought it was worth starting very concretely.

**Comment by njsmith** [comment]
Sorry, what are the proposed semantics for `depth_first` and `breadth_first`?

I'm not too excited about adding functionality to `ParkingLot` – generally `ParkingLot` has turned out to be way less useful than I originally expected. (Turns out that in async-land it's much easier to throw together a custom queueing data structure than in threads-land, and you don't need helpers like this as much.)

That said, seems like a reasonable enough approach to accomplishing your goals. I don't have a strong intuition about whether it's general purpose though to put upstream in trio proper, or more of a specialized tool that makes more sense as part of your app or a library. (And it doesn't sound like it particularly needs special access to trio internals that would require it to be upstream.) Maybe they will become more clear once I understand the details better?

**Comment by Zac-HD** [comment]
> Sorry, what are the proposed semantics for depth_first and breadth_first?

Using a new `Nursery._counter` attribute, we can define a DFS or BFS ordering of nurseries by taking advantage of their tree structure.  We can therefore define task priority as the ordering of their parent (or eventual-parent) nursery, breaking ties by the `Task._counter` integer ID.  

For example DFS would favor child nurseries over parents, and break ties between nurseries and between tasks in favor of the oldest.  BFS would favor tasks closer to the root nursery and break ties the same way.  This isn't a particularly sophisticated prioritization scheme, but if you just want some earliest-first streaming data processing this DFS approach seems pretty nice.

> I'm not too excited about adding functionality to `ParkingLot` – generally `ParkingLot` has turned out to be way less useful than I originally expected. ... That said, seems like a reasonable enough approach to accomplishing your goals. I don't have a strong intuition about whether it's general purpose though to put upstream in trio proper, or more of a specialized tool that makes more sense as part of your app or a library.

Yeah, I think I can implement a `PrioritizedLimiter` class downstream using only public APIs now, and 'if in doubt, start it downstream' is a good rule of thumb.  If it turns out to be particularly useful, I'll let you know and open a follow-up issue 🙂
