### ISSUE TITLE
Error in CI with Windows pypy-3.9-nightly on master

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2776]
```
 =========================== short test summary info ===========================
ERROR ..\..\..\_temp\146b9dda-2979-45d0-83a5-aafce08d7dac\pypy-c-jit-107681-7eff72a343df-win64\lib\site-packages\trio\_tests\test_dtls.py - SystemError: cpyext: Failure to allocate 'ABCMeta' (with a non-zero tp_itemsize) when len(obj) cannot be calculated
ERROR ..\..\..\_temp\146b9dda-2979-45d0-83a5-aafce08d7dac\pypy-c-jit-107681-7eff72a343df-win64\lib\site-packages\trio\_tests\test_highlevel_ssl_helpers.py - SystemError: cpyext: Failure to allocate 'ABCMeta' (with a non-zero tp_itemsize) when len(obj) cannot be calculated
ERROR ..\..\..\_temp\146b9dda-2979-45d0-83a5-aafce08d7dac\pypy-c-jit-107681-7eff72a343df-win64\lib\site-packages\trio\_tests\test_ssl.py - SystemError: cpyext: Failure to allocate 'ABCMeta' (with a non-zero tp_itemsize) when len(obj) cannot be calculated
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!
============================= 3 errors in 30.49s ==============================
```

Test run: https://github.com/python-trio/trio/actions/runs/5952689117/job/16235722709

I'm pretty sure this is caused by something upstream, I reran the test on ef6d8ee5cbaf63f9d71746a98638249e171b81ec which passed at the time, and it now fails.

**Comment by jakkdl** [comment]
Tried fixing with switching to `pypy-3.9` in #2825, but that just failed earlier. With #2678 both windows+pypy builds are now completely broken. Is it time to simply state that we don't support windows+pypy, or does anybody care to look into these?

**Comment by jakkdl** [comment]
ubuntu pypy-3.9-nightly also seem to be failing

**Comment by A5rocks** [comment]
I've mentioned the CFFI install failure over at https://foss.heptapod.net/pypy/pypy/-/issues/4005 and I thought the issue sounded like they were already fixing that, but I welcome looking at that more.

**Comment by CoolCat467** [comment]
Is this still an issue?

**Comment by A5rocks** [comment]
Possibly? We don't have CI for pypy on windows (or macos) atm

**Comment by jakkdl** [comment]
> Possibly? We don't have CI for pypy on windows (or macos) atm

they were removed from CI due to being broken, so yeah need to run tests to see if it's been fixed.

**Comment by A5rocks** [comment]
Given PyPy's Python 3.10 (the only thing they support nowadays) seems to work fine in https://github.com/python-trio/trio/pull/3074, I think this issue can be closed.
