### ISSUE TITLE
Incorrect line numbers in tutorial

### ISSUE THREAD

**Issue by shi-bmz** [python-trio/trio#2778]
In the ["Async functions" section](https://trio.readthedocs.io/en/stable/tutorial.html#async-functions) of the tutorial the line numbers in the paragraph containing "On line 17" appear to be off by -3 (i.e. 3 should be added to each line-number reference).

**Comment by jakkdl** [comment]
Fixed in master since https://github.com/python-trio/trio/pull/2711, only awaiting new release. But thanks for reporting!
