### ISSUE TITLE
typing error on master in _core/_multierror since exceptiongroup==1.1.3

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2783]
https://github.com/python-trio/trio/actions/runs/6043678194/job/16401102375#step:5:840
```
 ++ mypy trio --platform linux
trio/_core/_multierror.py:264: error: Signature of "derive" incompatible with supertype "BaseExceptionGroup"  [override]
trio/_core/_multierror.py:264: note:      Superclass:
trio/_core/_multierror.py:264: note:          @overload
trio/_core/_multierror.py:264: note:          def [_ExceptionT <: Exception] derive(self, Sequence[_ExceptionT], /) -> ExceptionGroup[_ExceptionT]
trio/_core/_multierror.py:264: note:          @overload
trio/_core/_multierror.py:264: note:          def [_BaseExceptionT <: BaseException] derive(self, Sequence[_BaseExceptionT], /) -> BaseExceptionGroup[_BaseExceptionT]
trio/_core/_multierror.py:264: note:      Subclass:
trio/_core/_multierror.py:264: note:          @overload
trio/_core/_multierror.py:264: note:          def derive(self, Sequence[Exception], /) -> NonBaseMultiError
trio/_core/_multierror.py:264: note:          @overload
trio/_core/_multierror.py:264: note:          def derive(self, Sequence[BaseException], /) -> MultiError
trio/_core/_run.py:204: error: Unused "type: ignore" comment  [unused-ignore]
Found 2 errors in 2 files (checked 129 source files)
++ EXIT_STATUS=1
```
bumped in #2782

**Comment by A5rocks** [comment]
Actually it's cause of a `exceptiongroups` bump -- I'm just not sure exactly why we use the whole assignment thing instead of just subclassing so I left that for a bit.

**Comment by jakkdl** [comment]
@CoolCat467 wrote the type stubs in #2742

**Comment by CoolCat467** [comment]
Basically there was a bit of a mess with overloads and the different overloads accepting things that were too broad and caught other branches of it.

**Comment by jakkdl** [comment]
> Basically there was a bit of a mess with overloads and the different overloads accepting things that were too broad and caught other branches of it.

you up for writing a PR to fix it?

**Comment by CoolCat467** [comment]
> > Basically there was a bit of a mess with overloads and the different overloads accepting things that were too broad and caught other branches of it.
> 
> you up for writing a PR to fix it?

Sure, I'll take a crack at it.

**Comment by CoolCat467** [comment]
#2787
