### ISSUE TITLE
Add pre-commit.ci

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2789]
As we have added pre-commit to the repo, I'd love to see https://pre-commit.ci/ added so we can continue testing it as a (partial) replacement for check.sh
@A5rocks was recently given the necessary permissions to do this after I asked about it on Gitter.

**Comment by TeamSpen210** [comment]
It'd also be good to look at the configuration for `builds.sr.ht`, remove it/fix it so it's not failing every PR.

**Comment by jakkdl** [comment]
> It'd also be good to look at the configuration for `builds.sr.ht`, remove it/fix it so it's not failing every PR.

opening a separate issue for it as I don't think it's related #2792

**Comment by A5rocks** [comment]
I've added pre-commit.ci. Let's see if this works!
