### ISSUE TITLE
Add async detection API.

### ISSUE THREAD

**Issue by tomchristie** [python-trio/trio#2802]
I'd like to be able to differentiate between `asyncio` and `trio` without adding an explicit dependency on `sniffio`.

Would either of the following be considered valid additions to the project API?...

```python
# Same as the 'sniffio' API, but explicitly available within trio...
trio.current_async_library()
```

```python
# Just is-it-trio aint-it-trio detection...
trio.is_running_trio()
```

**Comment by smurfix** [comment]
This may be a stupid question but … why would you want to do that? Trio already does depend on sniffio.

**Comment by tomchristie** [comment]
It's a good question... my motivation here is that *"if `import trio` succeeds, then so will `import sniffio`."* is implementation detail, that I shouldn't assume I can rely on.

If there's a public API then I don't need to be concerned about how `trio` implements it's detection, I just need to know that it provides an API for it.

**Comment by smurfix** [comment]
Well, the public API **is** sniffio. This is unlikely to ever change IMHO, esp. given that the main author of sniffio and trio happen to be the same person.
