### ISSUE TITLE
A simple question regarding using trio in http web servers

### ISSUE THREAD

**Issue by secureness** [python-trio/trio#2814]
```python
import trio
import asyncio
from aiohttp import web


async def handle(request):
    filepath = request.match_info.get('name', "Anonymous")
    async with await trio.open_file(filepath) as f:
        contents = await f.read()
    return web.Response(text=contents)


async def run_web_server():
    app = web.Application()
    app.add_routes([web.get('/trio', handle)])
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, 'localhost', 8000)
    await site.start()


async def run_other_task():
    while True:
        await asyncio.sleep(1)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.create_task(run_web_server())
    loop.run_until_complete(run_other_task())
    loop.run_forever()
```
I'm trying to work with trio file I/O in web servers but it seems that I don't have enough knowledge to do that, could you please help me a little bit here?

**Comment by A5rocks** [comment]
Unfortunately, aiohttp is based on (and relies on) asyncio very heavily. This means trio won't work. If I remember correctly, starlette / fastapi have trio support (through anyio) and probably more I'm forgetting.

If you want file io in asyncio, your best bet is a threadpool (iirc that's what trio does under the hood) or aiofile (which does that too).
