### ISSUE TITLE
`removal` newsfragments do not show in history

### ISSUE THREAD

**Issue by richardsheridan** [python-trio/trio#2846]
We have several removals pending and I was directed to make one in #2841, but `removal` is [not a valid towncrier type right now](https://github.com/python-trio/trio/blob/6c50dc2b747802fc3ad98a55071dad00f9fbaec9/pyproject.toml#L121-L154). Do we want to rename newsfragments, or add `removal` and remove `deprecated`, or maybe there is a way to alias them?

**Comment by A5rocks** [comment]
Yeah I noticed this and my conclusion is we should add a new removal type that mirrors deprecated. If you check the readme in the newsfragments folder it mentions both are for different things after all.

**Comment by oremanj** [comment]
My suggestion of `removal` in the `cancellable` -> `abandon_on_cancel` diff was incorrect; that should have been `deprecated`. I got confused by the other `removal` newsfragments, which I agree that we should support.
