### ISSUE TITLE
Failing to import if_indextoname on Android

### ISSUE THREAD

**Issue by Cheaterman** [python-trio/trio#2915]
Everything in the title - [see here for details](https://github.com/python-trio/trio/commit/59731c31b0ee0441d9f561f31ac0fdcc6cb99072#r136072321).

As the comment asks, would it be OK to re-add the `_suppress(ImportError)` context manager around these?

**Comment by CoolCat467** [comment]
Just wondering, this is `cpython` correct?

**Comment by Cheaterman** [comment]
Correct - we use CPython to deploy on Android/iOS, I don't think other interpreters are supported. :-)
