### ISSUE TITLE
When bumping sphinx, remove FrameType workaround in docs/source/conf.py

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2921]
https://github.com/sphinx-doc/sphinx/issues/11802
https://github.com/sphinx-doc/sphinx/pull/11861
being fixed should make
https://github.com/python-trio/trio/blob/d1cc062bfe5e0c2fd7f3c702cc4390cbfdb904f0/docs/source/conf.py#L200-L203

redundant. Though I had some issues with getting `TracebackType` working with their workaround previously:
https://github.com/python-trio/trio/blob/d1cc062bfe5e0c2fd7f3c702cc4390cbfdb904f0/src/trio/testing/_raises_group.py#L22-L24
that'll probably be the case with `FrameType` as well - and if so we should probably investigate and open an issue in sphinx about it.

**Comment by A5rocks** [comment]
This doesn't seem to work when updating Sphinx to 7.4.7

**Comment by jakkdl** [comment]
I spent a while digging around in sphinx, and it appears I was wrong about the cause being `types.FrameType.__module__ == 'builtins'. It's the same problem as with `math.inf`, where they're defined in the `py:data` section in the objects.inv file, rather than in `py:class`.

The open issues for this seem to be https://github.com/sphinx-doc/sphinx/issues/10974 / https://github.com/sphinx-doc/sphinx/issues/10974

**Comment by jakkdl** [comment]
pushed a commit to #3070 that fixes the comment, so we can probably close this. Don't think we need a dedicated tracking issue for it
