### ISSUE TITLE
Windows: wait_{read,writ}able limited to 512 sockets

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#3]
This is because we currently use `select.select`. The limit is entirely artificial -- the underlying `fd_set` object is just a (int length, array of SOCKET integers) structure which we could allocate at whatever size we wanted, if we wanted. Or we could use `WSAPoll`.

**Comment by njsmith** [comment]
Though note that `WSAPoll` is quirky:
* https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/18769abd-fca0-4d3c-9884-1a38ce27ae90/wsapoll-and-nonblocking-connects-to-nonexistent-ports?forum=wsk
* https://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/

**Comment by njsmith** [comment]
This should be considered in combination with #52.

**Comment by oremanj** [comment]
I think this is superseded by the plan in #52 to stop using select() entirely.
