### ISSUE TITLE
write a real README

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#30]

**Comment by NoneGG** [comment]
Is there a comparison (both about efficiency and usability) among asyncio, curio and trio?

**Comment by njsmith** [comment]
Regarding asyncio versus curio, see
https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/
-- all the nice features of curio there are also features of trio, since I
wrote both the blog post and trio :-)

Regarding trio versus curio, there isn't a great one stop document. There's
some discussion here: http://trio.readthedocs.io/en/latest/design.html

Regarding performance, that's also the document to look at, in particular
the first section.

**Comment by NoneGG** [comment]
@njsmith 
I read the first article when i am up to decide to use curio or asyncio, that was detailed and really helpful, i didn't realize that it is written by you, thank you.

I will check the second article right now.

**Comment by njsmith** [comment]
We have a README now, so closing
