### ISSUE TITLE
unexpected StopAsyncIteration

### ISSUE THREAD

**Issue by zoranbosnjak** [python-trio/trio#3028]
My intention is to wrap an existing generator `my_gen` such that a new (wrapped) generator would yield messages from the original generator and `None` on each timeout. The wrapped generator shall not end (unless the original generator ends). My attempt was something like:

```python
import random
import trio

async def my_gen():
    cnt = 0
    while True:
        cnt += 1
        await trio.sleep(random.uniform(0.1, 2.0))
        yield cnt

async def gen_wrapper(timeout, gen):
    while True:
        with trio.move_on_after(timeout) as cancel_scope:
            msg = await anext(gen)
            yield msg
        if cancel_scope.cancelled_caught:
            yield None

async def main():
    async for msg in gen_wrapper(1.0, my_gen()):
        print(msg)

trio.run(main)
```

The problem is that generator stops after a timeout, for example:

```
1
2
None
...
    async for msg in gen_wrapper(1.0, my_gen()):
RuntimeError: async generator raised StopAsyncIteration
```

... instead of something like:

```
1
2
None
3
None
None
4
... keep on running
```

So, how do I prevent the generator from being stopped? 
I have searched for similar issues, like #265, but I could not find any workaround to make `gen_wrapper` function work as expected.

**Comment by TeamSpen210** [comment]
One problem is that you're [yielding inside a cancel scope](https://trio.readthedocs.io/en/stable/reference-core.html#cancel-scopes-and-nurseries). That is very bad, it corrupts Trio's understanding of which scopes are currently active, and can cause any number of mysterious issues. In general you need to be very careful with async generators. In this case you could move the `yield msg` to an `else:` branch.

**Comment by zoranbosnjak** [comment]
@TeamSpen210 I have tried to move `yield` outside of cancel sope, like this:

```python
async def gen_wrapper(timeout, gen):
    while True:
        with trio.move_on_after(timeout) as cancel_scope:
            msg = await anext(gen)
        if cancel_scope.cancelled_caught:
            msg = None
        yield msg 
```

But I am getting the same problem. Any other idea?

**Comment by TeamSpen210** [comment]
Okay, looking at the traceback, I'm not sure if this wrapper is really possible the way you're defining it. The problem is that when the timeout occurs, `trio.sleep()` is going to raise a `Cancelled` exception. That exits out of the generator, and is caught by the cancel scope. But since it exited the generator, the generator has entirely failed and quit, so trying to iterate it again just immediately raises `StopAsyncIteration`. 

What would work better is to make `my_gen()` not be a generator at all. Instead make it a separate task, using a memory channel to send values to the wrapper with a 1-item buffer.

```py
import random
import trio

async def data_sender(channel: trio.MemorySendChannel[int]):
    cnt = 0
    while True:
        cnt += 1
        await trio.sleep(random.uniform(0.1, 2.0))
        await channel.send(cnt)

async def gen_wrapper(timeout, channel: trio.MemoryReceiveChannel[int]):
    while True:
        with trio.move_on_after(timeout) as cancel_scope:
            msg = await channel.receive()
        if cancel_scope.cancelled_caught:
            msg = None
        yield msg

async def main():
    async with trio.open_nursery() as nursery:
        send, rec = trio.open_memory_channel(1)
        nursery.start_soon(data_sender, send)
        async for msg in gen_wrapper(1.0, rec):
            print(msg)

trio.run(main)
```

**Comment by CoolCat467** [comment]
Yea, at the moment, it is not really possible for Trio or really any asynchronous library to take care of timeouts inside async generators, and both [PEP-533](https://peps.python.org/533) and [PEP-789](https://peps.python.org/789) are trying to fix this. Basically we can't really do anything other than try to give people warnings about this use case unless something changes in Python itself, at least as far as I understand.

**Comment by jakkdl** [comment]
You may consider running flake8-async with ASYNC900/unsafe-async-generator that will flag any uses of async generators https://flake8-async.readthedocs.io/en/latest/rules.html#optional-rules-disabled-by-default
