### ISSUE TITLE
Add a nursery method that returns a context manager that keeps the nursery open

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#304]
The functionality is already there for `trio.start`; `trio.serve_listeners` could also use it, on the `connection_nursery`.

**Comment by njsmith** [comment]
Looking at this again, I'm not as certain it's a good idea as I (apparently) was when I created it, so I'm switching the labels :-).

To clarify what the proposal actually is, though: normally a nursery is closed when all the tasks inside it exit. Say I have a nursery. I hand it off to some other code, which will stash it somewhere, and eventually – at some unknown point in the future – spawn tasks into it. This creates a possible race condition: the nursery was open at the time I handed it off, but what if it closes between when I hand it off and when the receiving code actually starts using it? If the receiving code could immediately mark the nursery as "in use", then it could solve the race condition. And we already have essentially this functionality, internally, via the `Nursery._pending_starts` attribute – the `Nursery.start` method uses it to make sure that if the nursery is open at the time `start` is called, then it will still be open when the task calls `task_status.started()`.

I'm having some trouble imagining exactly when this would be useful though. It's pretty unusual for someone to open a nursery in one task, pass it to a sibling, etc. Maybe it's really important, but I'd like it better if I had a clear example of a situation where all the pieces lined up to make it useful.

**Comment by smurfix** [comment]
I'd assume that the originator closes the nursery for a reason, which is that it wants to terminate stuff.
So starting another task into it then fails. Fine. You don't want that to happen, don't close the nursery. :-P

**Comment by njsmith** [comment]
"Close a nursery" isn't really an operation. I'm not talking about cancelling the nursery. Nurseries close themselves automatically when no-one is using them.

Anyway, the idea here is to help with the situation where code A opens the nursery, and then hands it off to code B. Code A doesn't know how long code B needs the nursery for, so it's hard for either side to control the lifetime on their own.

If such situations exist.

**Comment by smurfix** [comment]
Right, so if B wants to keep the nursery alive in the sense of "A leaving the nursery's scope shall not prevent new tasks from being spawned", then all it needs to do is to spawn a sleep-forever task into it (and cancel that when it exits).

A context wrapper that does this is ten easy lines of code, and the only interesting part is passing the sleeping tasks's cancel scope back to B via task_started(). That kind of thing belongs in a Trio cookbook but not in Trio proper IMHO.

**Comment by oremanj** [comment]
This is even easier now that we have unbound cancel scopes:
```
@contextmanager
def keep_nursery_open(nursery):
    cancel_scope = trio.CancelScope(shield=True)
    async def keep_open():
        with cancel_scope:
            await trio.sleep_forever()
    nursery.start_soon(keep_open)
    try:
        yield
    finally:
        cancel_scope.cancel()
```
Any updated thoughts on whether it would still be potentially desirable to have this in the core?

**Comment by njsmith** [comment]
We haven't found any use cases for this so far, so let's close it until we do.
