### ISSUE TITLE
Make sure trio works with Read the Docs Addons

### ISSUE THREAD

**Issue by A5rocks** [python-trio/trio#3064]
I saw https://about.readthedocs.com/blog/2024/07/addons-by-default/ and it looks like we might have to make some changes. Its not very clear to me what changes exactly though. And it seems the theme support for it is in a dev release so we should probably wait.

**Comment by A5rocks** [comment]
Should wait for RTD theme's 3.0 release.

**Comment by A5rocks** [comment]
FYI @humitos (since I don't want to fill out a random "support" form just for feedback) I don't think it was made very clear *what* RTD injected into `html_context`. I *just* realized that the version we were showing wasn't quite right (because we used `current_version`) and I suspect this might be common for anyone who customized the layout of the RTD sphinx theme (which uses that).

To show it isn't just me, I found that e.g. https://github.com/microsoft/torchgeo has this issue too. It's nothing big but if there's some obvious way for RTD to notify project owners about past `html_context` that might be appreciated.

**Comment by humitos** [comment]
> don't think it was made very clear _what_ RTD injected into `html_context`

Starting in the last October, Read the Docs injects _nothing_ into `html_context`. Read https://about.readthedocs.com/blog/2024/07/addons-by-default/

In the same blog post, there is a Sphinx extension mentioned that can be used to recover most of the injections done by Read the Docs in the past.

**Comment by A5rocks** [comment]
Yeah, I guess I didn't really think through the consequences of that as much as I should have. (Well, mostly just that I forgot how exactly our docs did things. I saw something about allcaps `READTHEDOCS` so used that and somehow missed the thing next to it...)
