### ISSUE TITLE
I got Process finished with exit code -1073740791 (0xC0000409) STATUS_STACK_BUFFER_OVERRUN when import trio

### ISSUE THREAD

**Issue by kjdsfbchkadwbcuiwbcfiw** [python-trio/trio#3091]
I met a problem when I import trio,it shows Process finished with exit code -1073740791 (0xC0000409) .
I use 3.12 for python and it was unrelated to IDE.
Is there any idea about how it happens ?

**Comment by A5rocks** [comment]
What OS? What happens if you import in `python -X dev`? (I'm not sure anything will change, but...)

**Comment by A5rocks** [comment]
My working hypothesis is that something is incorrect in your Python installation because to my knowledge trio shouldn't cause that.

**Comment by kjdsfbchkadwbcuiwbcfiw** [comment]
Thank you for answer！I am using windows and I got blow using python -X dev -c "import trio"

`python -X dev -c "import trio
Windows fatal exception: access violation

Current thread 0x0000ea1c (most recent call first):
Windows fatal exception: access violation`

**Comment by kjdsfbchkadwbcuiwbcfiw** [comment]
I just reinstalled a python to replace the old one, but it seems nothing change.

**Comment by A5rocks** [comment]
> Thank you for answer！I am using windows and I got blow using python -X dev -c "import trio"
> 
> 
> 
> `python -X dev -c "import trio
> 
> Windows fatal exception: access violation
> 
> 
> 
> Current thread 0x0000ea1c (most recent call first):
> 
> Windows fatal exception: access violation`

Well at least you're getting an access violation rather than an error about the stack here. I think `-X dev` enables faulthandler, but maybe `python -X faulthandler -X dev -c "import trio"` gets more information?

What major version of Windows are you using? (Probably irrelevant because if I had to suspect anything (now that it wasn't Python) it would be something you installed or drivers but...)

**Comment by kjdsfbchkadwbcuiwbcfiw** [comment]
Thank you for reply! It get same output using python -X faulthandler -X dev -c "import trio"
`python -X faulthandler -X dev -c "import trio"
Windows fatal exception: access violation

Current thread 0x00008714 (most recent call first):
Windows fatal exception: access violation`

I am now using windows 11.

**Comment by A5rocks** [comment]
Alright. Does this happen when you run just `python -X dev`? Does it happen if you try `python -X dev -c "import cffi"`?

**Comment by kjdsfbchkadwbcuiwbcfiw** [comment]
No, it won’t happen

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/19/2024 23:23 |
| To | python-trio/trio ***@***.***> |
| Cc | kjdsfbchkadwbcuiwbcfiw ***@***.***>,
Author ***@***.***> |
| Subject | Re: [python-trio/trio] I got Process finished with exit code -1073740791 (0xC0000409) STATUS_STACK_BUFFER_OVERRUN when import trio (Issue #3091) |

Alright. Does this happen when you run just python -X dev? Does it happen if you try python -X dev -c "import cffi"?

**Comment by A5rocks** [comment]
Did you ever figure this out or did it fix itself?

**Comment by A5rocks** [comment]
I'll close this, let me know if you get this again/feel free to reopen.
