### ISSUE TITLE
Drop python3.8 support

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#3104]
3.8 is EOL since 2024-10-07, so we can now drop support for it. This includes CI updates, running pyupgrade (which ruff looks like it reimplements), and identify 3.8-specific code and tests that can be removed.

(We can also edit the CI config to indicate 3.13 is fully released, and experiment with adding 3.14 to CI when there are builds available)

**Comment by graingert** [comment]
I don't think this is a good first issue. There's lots of fiddling around with linters involved
