### ISSUE TITLE
Guest mode thread wrapping

### ISSUE THREAD

**Issue by NicolasT** [python-trio/trio#3174]
For a somewhat particular use-case involving interactions with a non-Python runtime, I'd need to be able to run some code "around" the code running in a thread (in this thread) when guest mode is used (essentially, in order to be able to call the callable passed as `run_sync_soon_threadsafe` which uses this other runtime "safely").

Since the moment the thread gets started is unknown, and a `ThreadCache` is used, monkey-patching `threading.Thread` or similar around the call to `start_guest_run` doesn't cut it.

Looking into the implementation, I was thinking of two approaches:

1. Allow passing a callable `start_thread_soon` to `start_guest_run` which takes the arguments `_thread_cache.start_thread_soon` takes and "does what's expected" (potentially not using a thread cache), or
2. Allow passing an instance of a type that implements `contextlib.AbstractContextManager` to `start_guest_run`, and this context-manager is then wrapped around whatever gets called in the thread (using `_thread_cache.start_thread_soon`). Here, if none given, some no-op context-manager would be used as a default.

Does this sound like a reasonable use case? If so, any preference for an API to support this, or any ideas for other work-arounds?

**Comment by oremanj** [comment]
I think supporting an alternative `start_thread_soon` would be pretty easy and low-impact to the implementation, and I can think of other cases besides yours that would benefit from it, so that would be my preference.

I'm curious about the details of what you're trying to interface with here though, because it sounds like a surprising API. It's not really possible to wrap something "around" the thread by wrapping `start_thread_soon`, because the thread keeps running after the starting code has moved on with its life (exited the context manager, etc). If it's just setting a contextvar or similar, you might be able to achieve the same goal by wrapping the context manager around the call to `start_guest_run`.

**Comment by NicolasT** [comment]
> I'm curious about the details of what you're trying to interface with here

Code using the other language/runtime can construct Python objects (including callable ones) and pass them to Python code through bindings to `libpython`. However, calling actual functions using the runtime (i.e., a function wrapped by some Python callable in this case), the thread from where it's invoked needs to be registered with the runtime (and unregistered before thread exit) for GC tracking purposes (among other things).

So what I'd need is something like (pseudo-code, obviously)

```
def run_guest_mode(...):
    # ...
    # invoke run_sync_soon_threadsafe as needed
    # ...

def guest_mode_worker(...):
    # Runs in non-main-thread
    register_thread_with_runtime()
    try:
        run_guest_mode(...)
    finally:
        unregister_thread_from_runtime()

def start_guest_run(...):
    # ...
    t = threading.Thread(target=guest_mode_worker)
    t.start()
    # ...
```

Somewhat similar to `PyThreadState_New`/`PyEval_RestoreThread`/`PyInterpreterState_Clear` and friends.

**Comment by oremanj** [comment]
Oh, I see, I misunderstood - you need to wrap the thread target function, not the `start_thread_soon` call, but wrapping `start_thread_soon` gives you enough leverage to do the actual wrapping of the thread target function that you want. Yes, I think allowing overriding `start_thread_soon` is your best option here.

**Comment by NicolasT** [comment]
What I didn't notice before but now saw in the code, also guided by your comments above, is that every `get_events` call runs, potentially, in a different thread, and there's no "long running" operation. So swapping out `start_thread_soon` could be tricky to implement properly, and the context-manager approach wouldn't really work either: it'd essentially be "as good" (bad?) as doing the thread register/unregister call in a (Python) wrapper around the call to `run_sync_soon_threadsafe`, and hence only "survive" this call, not the entire lifetime of the thread.

I guess my initial approach would require changes in in `ThreadCache`, which is quite internal, as in, unclear how this functionality could be exposed.
