### ISSUE TITLE
You can improve the run？

### ISSUE THREAD

**Issue by InfernalAzazel** [python-trio/trio#3178]
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/fe0ddfe6-4b76-4555-a004-99aeb1884ec1" />

**Comment by TeamSpen210** [comment]
This is a [PyCharm bug](https://youtrack.jetbrains.com/issue/PY-74136/PyCharm-expects-a-parameter-for-a-variadic-argument-annotated-with-TypeVarTuple-when-it-is-empty), it has issues when `*args` is empty.
