### ISSUE TITLE
Closing a stream doesn't affect readers

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#341]
If a stream is read from in task A and closed in task B, one would assume that the `await receive_some()` called by A reads an EOF, raises an exception, gets cancelled, or whatever.

Instead, it just sits there, doing nothing.

The underlying reason is that closed file descriptors are silently removed from `epoll`. Apparently, that is regarded as a feature. As certain other asyncio libraries are able to handle this situation, we need to at least document that.

**Comment by njsmith** [comment]
Yeah, you're totally right -- it's impossible to handle this perfectly without more help from the OS, but we could definitely handle 99% of cases, and that's #36, so closing this in favor of that to keep the discussion consolidated.
