### ISSUE TITLE
Can we do something better for macos testing?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#366]
Travis's MacOS support is dreadfully slow these days. I pushed a new commit to a PR at ~7:30pm California time, which is outside working hours everywhere in the US and Europe, and 2.5 hours later it still hasn't started running one of the MacOS jobs.

I don't think there's any way to bribe/bully/blackmail travis into working better, short of switching to one of [their private plans](https://travis-ci.com/plans). I guess we could ask. But they know about the problem, they have no capacity to add, and it's not like we particularly deserve special treatment somehow.

CircleCI offers a [free "seed" sized MacOS plan for OSS projects](https://circleci.com/pricing/#build-os-x). This gives 2x concurrency (which is all we need for any given commit anyway), and 500 minutes a month of build time. On Travis currently we're at ~5 min of MacOS build time per commit; I don't know if CircleCI is comparable or not. But if so that would give us ~100 builds a month, which ... might be enough for our current needs? I'm a little nervous because our needs could grow without much warning, and glancing over the travis build history right now my guesstimate is we're doing >50 builds a month, so there's not a ton of headroom. But it's probably worth trying, since the current setup is miserable and all the numbers I just quoted are very approximate -- maybe it'd be totally fine.

Or we could try making puppy-dog eyes at @reaperhulk and see if he's willing to let us piggy-back on pyca/cryptography jenkins infrastructure.

**Comment by reaperhulk** [comment]
I'd be willing to add python-trio as an org on our Jenkins. A few things needed + caveats:

* Jenkins needs a user or API key (but preferably a user honestly) that can write commit statuses to the repo if you want to see feedback on builds.
* You'll need to give me the codecov token if you want to merge coverage from the macos builders in jenkins with the rest of your CI
* I can't give you much (any) control over the actual config of the jenkins jobs so if you need changes you'll have to push through whatever degree of ennui I'm currently experiencing to convince me to do something. That said you will get Jenkinsfile so you've got a pretty reasonable degree of control available via source controlled configuration.
* PyCA's needs will take precedence so if necessary I might disable your job temporarily. This is unlikely (your needs are quite modest and I don't really foresee a scenario where a PyCA project would need to save a few minutes so badly) but I don't want there to be confusion about my priorities 😄 

Here's a potential jenkinsfile that could run the trio tests. Untested for now.

```
def configs = [
    [
        label: 'sierra',
        pyversions: ['python3.5', 'python3.6'],
    ],
]


def checkout_git(label) {
    retry(3) {
        def script = ""
        if (env.BRANCH_NAME.startsWith('PR-')) {
            script = """
            git clone --depth=1 https://github.com/python-trio/trio
            cd trio
            git fetch origin +refs/pull/${env.CHANGE_ID}/merge:
            git checkout -qf FETCH_HEAD
            """
            sh """#!/bin/sh
                set -xe
                ${script}
            """
        } else {
            checkout([
                $class: 'GitSCM',
                branches: [[name: "*/${env.BRANCH_NAME}"]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[
                    $class: 'RelativeTargetDirectory',
                    relativeTargetDir: 'trio'
                ]],
                submoduleCfg: [],
                userRemoteConfigs: [[
                    'url': 'https://github.com/python-trio/trio'
                ]]
            ])
        }
    }
    sh """
        cd cryptography
        git rev-parse HEAD
    """
}
def build(pyversion, label) {
    try {
        timeout(time: 30, unit: 'MINUTES') {

            checkout_git(label)

            withCredentials([string(credentialsId: 'trio-codecov-token', variable: 'CODECOV_TOKEN')]) {
                withEnv(["LABEL=$label", "PYVERSION=$pyversion"]) {
                    ansiColor {
                        sh """#!/usr/bin/env bash
                            set -xe
                            # Jenkins logs in as a non-interactive shell, so we don't even have /usr/local/bin in PATH
                            export PATH="/usr/local/bin:\${PATH}"
                            export PATH="/Users/jenkins/.pyenv/shims:\${PATH}"
                            cd trio
                            virtualenv .venv -p $PYVERSION
                            source .venv/bin/activate
                            python setup.py sdist --formats=zip
                            pip install dist/*.zip

                            pip install -Ur test-requirements.txt

                            mkdir empty
                            cd empty

                            INSTALLDIR=$(python -c "import os, trio; print(os.path.dirname(trio.__file__))")
                            pytest -W error -ra --run-slow ${INSTALLDIR} --cov="$INSTALLDIR" --cov-config=../.coveragerc --verbose

                            coverage combine
                            pip install codecov && codecov
                        """
                    }
                }
            }
        }
    } finally {
        deleteDir()
    }

}

def builders = [:]
for (config in configs) {
    def label = config["label"]
    def pyversions = config["pyversions"]

    for (_pyversion in pyversions) {
        def pyversion = _pyversion

        def combinedName = "${label}-${pyversion}"
        builders[combinedName] = {
            node(label) {
                stage(combinedName) {
                    build(pyversion, label)
                }
            }
        }
    }
}

parallel builders
```

**Comment by njsmith** [comment]
In the end it took 3h15m for travis to schedule that macos job tonight, and then it seems to have wedged itself at startup, so I guess I have to restart it? Ugghhh.

@reaperhulk That is super-generous, thank you! And those restrictions seem very reasonable :-).

To make sure I understand, my todo list for making this happen is like:

* Registering a new github user like "trio-jenkins", giving it write access to the trio repo, and giving you the password (?)
* Sending you our codecov token (that's easy)
* Dump that blob of... groovy?... whatever it is into a file called `Jenkinsfile` in the root of the `trio` tree

Anything else?

**Comment by njsmith** [comment]
@reaperhulk oh, and what's your preferred secret-transfer mechanism? keybase chat, for that blockchain cred?

**Comment by reaperhulk** [comment]
Let's hold off on step 1 here and we can see if the jenkins plugins in question have resolved their issues with personal access tokens. With a token we should be able to scope to just writing commit status... Probably going to prove impractical but we can dream.

To send a secret just hit me on IRC and we can do magic-wormhole.

One other item: You'll need to add a webhook for your org with payload URL https://ci.cryptography.io/github-webhook/

It should send events for: pull request, push, and repository. This will make it so jenkins gets notified on PR and master merge activity.

**Comment by njsmith** [comment]
I owe @reaperhulk several beers.
