### ISSUE TITLE
Simplify cancel_shielded_checkpoint ?

### ISSUE THREAD

**Issue by touilleMan** [python-trio/trio#395]
I'm not sure what is the need for a mix of `yield` and `asyncfunction` decorator here:

https://github.com/python-trio/trio/blob/a351a2d148032dccf2b06636efbf4399bc0e24a4/trio/_core/_traps.py#L13-L45

From what I understand, it is because an awaited object must be of a type with an `__await__` method.
But in such a case there could be a much simpler wait to do this:

```python
class CancelShieldedCheckpointType:
    def __await__(self):
        yield self
CancelShieldedCheckpoint = CancelShieldedCheckpoint()
del CancelShieldedCheckpointType

async def cancel_shielded_checkpoint():
    return await CancelShieldedCheckpoint
```

This way `CancelShieldedCheckpointType` is just a helper class (hence destroyed as soon at it is no longer needed) and `CancelShieldedCheckpoint` is still a singleton, this time compatible with `await` syntax.

**Comment by njsmith** [comment]
Hmm, you're right, that code does look kinda overcomplicated. I'd rather not create `__await__` methods just for this, but what do you think of #397?

**Comment by touilleMan** [comment]
Looks good to me :+1:

**Comment by njsmith** [comment]
Want to click merge, then? :-)

**Comment by touilleMan** [comment]
That would be an honor !

**Comment by njsmith** [comment]
Thanks! BTW, sorry I haven't followed up with pytest-trio stuff recently -- I'm hoping to get back to that soon, maybe this weekend.
