### ISSUE TITLE
asyncio coroutine/yield from broken

### ISSUE THREAD

**Issue by matham** [python-trio/trio#396]
I'm working on a library that supports py3.4+, to which I'm adding async (mainly trio) support. Because I can't use `await` and `async` keywords, I use the `coroutine` decorator and `yield from`. This worked fine earlier, however, now using trio master I'm getting an exception.

Is this intentional or a bug? Example code:

```py
from asyncio import coroutine
import trio

@coroutine
def do_something():
    yield from trio.sleep(1)

trio.run(do_something)
```

prints
```
Traceback (most recent call last):
  File "G:/Python/libs/Playground/src/playground2.py", line 10, in <module>
    trio.run(do_something)
  File "E:\Python\Python35-x64\lib\site-packages\trio\_core\_run.py", line 1225, in run
    return result.unwrap()
  File "E:\Python\Python35-x64\lib\site-packages\trio\_core\_result.py", line 119, in unwrap
    raise self.error
  File "E:\Python\Python35-x64\lib\site-packages\trio\_core\_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "E:\Python\Python35-x64\lib\site-packages\trio\_core\_run.py", line 921, in init
    async_fn, args, system_nursery, None
  File "E:\Python\Python35-x64\lib\site-packages\trio\_core\_run.py", line 792, in spawn_impl
    .format(coro)
TypeError: start_soon got unexpected <generator object do_something at 0x000001A96D022258> – are you trying to use a library written for asyncio/twisted/tornado or similar? That won't work without some sort of compatibility shim.
```

**Comment by njsmith** [comment]
Huh, yeah, I haven't thought about this at all because Trio doesn't support 3.4. How are you even importing Trio on 3.4?

**Comment by matham** [comment]
Oh, I didn't test on 3.4... only on 3.5. But I can always put the trio import under a version guard. It has to be source compatible with 3.4, so even if I exclude 3.4 from the async support I cannot use the `async` keyword.

The library has an option to use either trio or ayncio as the backend. It's not implementing any complex async stuff so it's mainly just providing coroutines with `yield from` and `@coroutine` so they can use either trio or asyncio depending on config. I recommend they use trio with it, but I wouldn't want to exclude asyncio.

**Comment by njsmith** [comment]
Well, let's check the easy (for me ;-)) options first.

Any chance you can increase your minimum version to 3.5? 3.4 stopped receiving bug fixes ~2 years ago and we're only ~6 months from 3.7 coming out...

Would it be easy to put all of your async support behind a version guard? (asyncio has received a lot of fixes since 3.4 as well...) E.g.

```python
try:
    from .async_api import *
except SyntaxError:
    pass
```

If you do have to keep supporting 3.4, do you know what the timeline is for dropping that? Even if we did hack around this for now it'd be difficult to keep working without a lot of testing effort...

**Comment by matham** [comment]
Pulling out the async code to a separate files will work - in fact I had already mostly done this to also be py2 compatible (because of `yield from`). The main issue was 3.4, but looking through my code dropping (or never offering) the async support for < 3.5.2 is alright and would require minimal changes.

Feel free to close the issue if you don't think it's something you'll change in trio.

**Comment by njsmith** [comment]
Ok, great – thanks for being flexible :-). It's always tricky to figure out the right trade off here, and I guess I might reconsider if a lot of folks show up asking for 3.4 support, but for now I think I'm going to stick to 3.5 as the baseline. (And for serious async development, I highly recommend using the latest Python release, given how fast things are moving in this area!)
