### ISSUE TITLE
Make trio.TaskLocal work in non-async scope

### ISSUE THREAD

**Issue by Nikratio** [python-trio/trio#417]
As the Trio documentation rightly says about including a request identifier in log messages:

> Now, here’s the problem: how does the logging code know what the request identifier is? One approach would be to explicitly pass it around to every function that might want to emit logs… but that’s basically every function, because you never know when you might need to add a log.debug(...) call to some utility function buried deep in the call stack, and when you’re in the middle of a debugging a nasty problem that last thing you want is to have to stop first and refactor everything to pass through the request identifier! 

And indeed, task local storage provides a nice solution for retrieving the request identifier :

```
task_info = trio.TaskLocal(conn_id=None)
def log_filter(record):
    if task_info.conn_id is None:
        return

    record.msg = '(conn %d) ' + record.msg
    record.args = (task_info.conn_id,) + record.args
```

But there is a problem: the log_filter needs to be added to every log handler - it's not enough to just add it to the local logger because then it won't be applied all the way down to the call chain, and we can't add it to the root logger because it is not inherited. This is a little ugly, but can be worked around by running something like:

```
     # Add connection information
    for handler in root_logger.handlers:
        handler.addFilter(server.log_filter)
```

..after all logging has otherwise been initialized.

But, there is always going to be that annoying bit of code that tries to log something before the event loop has started, giving us a `RuntimeError: must be called from async context` when accessing task_info.

Thus my question: can't access to the task local object outside of an async context just return the default value? Having to catch a `RuntimeError` when accessing an attribute is nasty.

**Comment by njsmith** [comment]
That seems reasonable. Want to submit a patch?

Note that we'll probably replace the TaskLocal API soon with one based on the PEP 567 ContextVar API, which basically adds a native version of task locals into the interpreter. (The PEP hasn't been finalized yet, but probably will be this week.) But this is a pretty small change so there's no reason to wait on it.
