### ISSUE TITLE
Write a CONTRIBUTING.md

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#46]
Some points to mention:

* A test for every change

* Keep the docs updated (uh... once we have docs)

* Keep the test suite fast – no sleeping!

* Speedups are awesome, but need: (a) microbenchmarks to demonstrate the change does what you expect, (b) data from some real use case to demonstrate that it matters or (c) doesn't complicate code. That's (a AND (b or c)).

* Notes on issue labels (e.g. "todo soon" means "not aware of any big questions here, the idea is good and the plan seems straightforward")

Can probably crib most of it from someone else...

**Comment by njsmith** [comment]
Cory's documents for hyper look pretty good

**Comment by njsmith** [comment]
Should include a pointer to https://trio.readthedocs.io/en/latest/design.html, which has a number of notes on both high- and low-level design conventions we follow.

**Comment by njsmith** [comment]
Also useful:

* https://mozillascience.github.io/working-open-workshop/contributing/
* https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

More things to include:

* explanation of our unusual commit bit policy, and orientation information for confused invitees
* pointer to #200

**Comment by njsmith** [comment]
Docs:
* general notes ("all public APIs should be documented")
* Link to the napoleon examples for google-style docstrings, it's a handy reference
* explain about nitpick mode and [`nitpick_ignore`](http://www.sphinx-doc.org/en/stable/config.html#confval-nitpick_ignore)

changelog -- if we implement towncrier then it needs to be described here

code formatting -- #221

**Comment by njsmith** [comment]
When documenting our commit bit policy, we should make it clear that contributing code is [*not* the only form of contribution that we value](https://www.unroutable.me/blog/2017/4/8/part-of-that-world). Probably we should refer to it as "joining the team" or similar (rather than exclusively emphasizing the commit rights part), and be explicit that getting a PR merged to directly improve the code or docs or infrastructure is one (particularly clear-cut) way to do that, but if you want to help by with planning, bug triage, helping new users, graphic design, ... then that also totally qualifies you to join the team.

**Comment by njsmith** [comment]
This is lovely: https://github.com/Unidata/MetPy#contributing

**Comment by njsmith** [comment]
The WeAllJS contributing.md and code_of_conduct.md generators look pretty neat too: https://github.com/WeAllJS

**Comment by njsmith** [comment]
Should include this magic link: https://stackexchange.com/filters/289914/trio-project-tags-on-stackoverflow-filter
that lets someone sign up to get notified of any trio-related questions on SO. Also lets me find it again b/c it's extremely well hidden :-)

**Comment by Fuyukai** [comment]
This got done (quite a while ago), closing.
