### ISSUE TITLE
Should ContextVar changes inside a nursery block be preserved after the nursery ends?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#496]
@oremanj raised [an excellent question on gitter](https://gitter.im/python-trio/general?at=5ad163b66d7e07082bf1dca6) ([see also](https://gitter.im/python-trio/general?at=5ad17b9327c509a7740e6314)): we generally try to make the code that runs inside an `async with` nursery block "act like" its a task inside the nursery. One place where this falls down is that the nursery block shares a `ContextVars` context with the outer process, so for example:

```python
async def main():
    cvar = contextvars.ContextVar()
    cvar.set("outer")
    async with trio.open_nursery() as nursery:
        assert cvar.get() == "outer"
        cvar.set("inner")
    assert cvar.get() == "inner"
```

OTOH if we move the nursery block into its own task, then we get different behavior:

```python
async def main():
    cvar = contextvars.ContextVar()
    cvar.set("outer")
    async with trio.open_nursery() as nursery:
        async def inner():
            assert cvar.get() == "outer"
            cvar.set("inner")
        nursery.start_soon(inner)
    assert cvar.get() == "outer"     # XXXXXX notice this line is different!
```

Is this a bug? Should the code inside the nursery block get its own shallow-copied `Context`, like child tasks do? I am genuinely not sure!

Technically it's certainly possible, though as @oremanj points out there is a a bit of trickiness required: in order to change contexts, you have to round-trip through the run loop (so that it can do `Context.run` with the new context). Currently nursery creation (the `__aenter__` method) is async-colored but is documented not to checkpoint; we could preserve this (if we care) by having a special change-`Context` trap that yields to the run loop but doesn't check for cancellation and immediately resumes the same task without going through the scheduler.

Really, though, it comes down to what users find least confusing, and I don't have a strong intuition here at all.

There are other places where the pseudo-task inside the nursery block is "special". For example, introspection APIs like `task.parent_nursery` reveal the messy reality. I've wondered if we should change this somehow, for example by actually creating a child `Task` object for the code inside the block (and unscheduling the parent `Task` until the child finishes). This would mean the two `Task` objects share the same coroutine object, which is kinda weird, but technically possible. However, even then, there are still cracks in the facade: Python's stack introspection still works the same, so if a debugger tried to get a traceback on those two tasks, then instead of seeing the parent's stack on the parent task and the child's stack on the child task, it would see two copies of the combined parent+child stack, which is pretty confusing. (Maybe we could hack this by providing our own traceback extraction functionality and keeping track of which frame created the nursery...?)

And, of course, Python's scoping rules still apply, so code inside the `async with` block can see and mutate local variables defined outside it. (Which is very similar to this issue, just with s/ContextVar/local var/!) So we're never going to make the nursery block *exactly* like a child task... again, I'm not sure :-).

**Comment by smurfix** [comment]
Hmm.

My intuition is that the pseudo-task works like a real task as far as the nursery's task handling is concerned, but it doesn't look like a separate task when you look at the code. What's more, all of contextvars, Python scoping, and debugger introspection agree with that.

So document that the inner task is "somewhat" special, but otherwise let's keep things the way they work now. You want something that behaves like a separate task in all respects? start a separate task.

**Comment by touilleMan** [comment]
I totally agree with @smurfix, beside ContextVars is something coroutine-related so I would not expect an `async with` to have something to do with it

**Comment by njsmith** [comment]
Fair enough.
