### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by zmitchell** [python-trio/trio#506]
In the description of [`BrokenStreamError`](http://trio.readthedocs.io/en/latest/reference-io.html#trio.BrokenStreamError) there is the following line (emphasis mine):

> Raised when an attempt to **use a stream a stream** fails due to external circumstances.

**Comment by njsmith** [comment]
Nice catch, and thanks for letting us know!

Would you be interested in putting together a PR to fix it?

**Comment by zmitchell** [comment]
Sure, I’ll do it today
