### ISSUE TITLE
should UnboundedQueue have logic to smooth out bursts to reduce latency spikes?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#51]
Right now, `UnboundedQueue` strongly encourages users to process all queued events in a single iteration. So for example, the `Nursery` `__aexit__` logic reaps all dead tasks before yielding. In general, this is a Good Thing, because it means that queue consumers can't fall behind -- basically it's applying backpressure to the world.

But one case where it might not be so good is if queue traffic is very bursty. So for example consider a nursery where on successive passes through the loop, it sees the following pattern of deaths: 0, 0, 1, 10000, 0, 0, 1, 0, 0. Here it might be better if we take that 10000 and spread them out over the next few cycles, since we can do this without falling behind, and it avoids blocking the run loop for so long at a time.

So one can imagine an UnboundedQueue that absorbs the 10000 task burst and meters it out into smaller batches.

OTOH, if the pattern of deaths is 0, 0, 1, 10000, 10000, 10000, 10000, then we really should be processing 10000 deaths in a cycle! So this is the tricky bit -- finding a control law that says how many items to allow through at any given moment, that smooths out bursts but never falls arbitrarily far behind.

**Comment by Fuyukai** [comment]
UnboundedQueue was removed, so this no longer applies.
