### ISSUE TITLE
big picture & beyond Python

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#557]
I see the benefit of the nursery and cancellation control structures presented by Nathaniel.  Also Trio's stance of avoiding threading, along with merging scheduling and cancellation concepts makes sense.  Relegating all concurrency interaction to cooperative, explicit switching within a single thread seems to be a clear sweet spot for Python given the GIL and CPU-bound threading issues.

What I'm trying to reconcile is how to apply these concepts elsewhere.  For example, Lua doesn't have a GIL issue.  So do we borrow the nursery and cancellation, but allow full threading (and associated headaches) to enable scaling to multiple cores?  Or would limiting preemptive multitasking to the equivalent of run_sync_in_worker_thread() be sufficient for 99% of use cases?  Or how about allowing individual threads to each run their own Trio event loop with all state thread-local, and somehow have apps carefully dispatch work to each thread?

Another question:  how well can a library like Trio be implemented in languages lacking colored function support?  (E.g. Lua or D language)

**Comment by tgoodlet** [comment]
>Or how about allowing individual threads to each run their own Trio event loop with all state thread-local, and somehow have apps carefully dispatch work to each thread?

@belm0 FWIW I have this working quite well under a minimal actor model [here](https://github.com/tgoodlet/tractor/tree/draft_readme). Though no larger uses (yet) to prove these concepts can scale, the adherence to `trionic` principles is demonstrating much easier to understand failure modes so far. `tractor` also uses [`multiprocessing`](https://docs.python.org/3/library/multiprocessing.html) so there is no GIL constraint and the *thread-local state* is implicit.

I personally am **very** interesting to see how `trionic` concepts can adapted in new languages and threading models. Given this recent project, I'm starting to think the lifetime and cancellation constraints can be applied to distributed processes on a much grander scale (under certain caveats) with good results.

You should give it a shot in lua and tell us your results!
I for one would be very interested as I think lua is a lovely minimalist language.
>Another question: how well can a library like Trio be implemented in languages lacking colored function support? (E.g. Lua or D language)

IIRC the [coroutine](http://lua-users.org/wiki/CoroutinesTutorial) support is there and could be paired with a [with statement](http://lua-users.org/wiki/WithStatement) solution and allow for designing something quite similar to `trio`. The lack of GIL should avoid the need to go full message passing between threads (if that's what you're after) - a [fast queue](https://stackoverflow.com/a/18844036/4200924) could do the trick?

**Comment by jab** [comment]
As mentioned in https://twitter.com/vorpalsmith/status/1040777480473214976
> apparently Kotlin is redoing its whole coroutine API based on ideas from Trio

https://github.com/Kotlin/kotlinx.coroutines/issues/410

🎉

**Comment by imrn** [comment]
Can you provide some technical details?

**Comment by oremanj** [comment]
Closing this in favor of the "structured concurrency" topic on the Discourse forum, since there's no action item.
