### ISSUE TITLE
trio_asyncio: needs a hook for "await future" et al.

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#568]
Over in https://github.com/vxgmichel/aiostream/issues/17#issuecomment-408337365 …:

> @smurfix the yield here is really an await, and trio-asyncio certainly has to intercept those or else await future wouldn't work :-)

Funny you should say that because, well, it doesn't. Not in native mode, anyway. (Compatibility mode nicely papered over this large crack.) The fun part is that outside the asyncio testsuite "await future" appears to be a really uncommon thing to do – otherwise we'd have run into that problem already.

Adding an intrusive interceptor for awaitables that trio doesn't understand would slow down the whole thing like crazy. So, could we instead think about adding an appropriate hook to Trio? Stored in the task's contextvar?

A sync procedure that gets the returned object and the Trio task, and returns a proper Trio `WaitTaskRescheduled` object, would probably work. I'll test that.

**Comment by smurfix** [comment]
Never mind. I've been stupid.

**Comment by njsmith** [comment]
Nesting two coroutine runners is confusing!
