### ISSUE TITLE
trio.Queue's qsize/full/empty methods -- should they report actual usage, or "virtual" usage?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#63]
Currently the `qsize`, `full`, and `empty` methods on `trio.Queue` are all based on the number of objects currently in the underlying deque container. But this is somewhat misleading: it isn't the case that `full` being False implies that a `put_nowait` will succeed, and it isn't the case that `empty` being False implies that a `get_nowait` will succeed. The reason is our fairness control: if there are 2 objects in the queue, and 2 tasks blocked in `get`, then those objects are "earmarked" to go to those tasks; similarly if there are 2 free slots and 2 tasks blocked in `put`.

Maybe it would be less confusing all around if we switched it so that these methods were based on the "virtual" size of the queue, i.e. the number of items after currently-fulfillable outstanding requests are fulfilled? Basically this would mean changing `qsize` to return `self._get_semaphore.value` instead of `len(self._data)`.

**Comment by njsmith** [comment]
We might want to rethink exactly what we put in the `statistics` output too.

**Comment by njsmith** [comment]
Note that this also applies (to a lesser extent, but still) to `UnboundedQueue`

**Comment by Fuyukai** [comment]
Queues were removed and replaced with channels, so this no longer applies.
