### ISSUE TITLE
Should we propagate back-pressure to spawn()?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#64]
So... here's a slightly wacky idea. I have no idea if this is a good idea, but writing it down so it doesn't get lost.

Right now, we use an `UnboundedQueue` for handling task deaths, because there's no meaningful way to apply backpressure to task deaths. If we're getting overwhelmed by too many tasks dying, then just logically speaking the only thing that would help is to throttle task *spawning*, not task death reporting.

So... are there circumstances where we should we throttle task spawning? In the new "nursery" design we actually have enough information to do this in a relatively directed way.

Random thoughts:
* This would require making `spawn` async again. I don't think this really bothers me; the vast majority of users are async anyway.
* What should the throttle criteria be? The naive one based on the queue idea would be that if there are more than N unreaped zombies then block spawn until the number drops below N. But this is a bit weird and indirect – and in particular it doesn't stop us from building up a huge number of living tasks, more than we can handle.
* In fact reaping tasks is pretty darn cheap; while the theoretical problem is real, it's unlikely that reaping per se is going to fall behind and cause problems
* If `spawn` blocks, then something like a socket listener task is going to show slightly nasty behavior where it stops accepting new connections until `spawn` unblocks. Or maybe that's... good? That's basically the idea of load shedding, after all. But... doing this seriously would require a much more nuanced way to specify policies than "number of unreaped zombies".
* Maybe we should be figuring out how to design such policies? Or more likely, how to provide a simple rough-but-good-enough-for-most-cases policy that can be overridden by more sophisticated versions on a case-by-case basis, similar to how nurseries are a simple supervisor + a substrate for more sophisticated supervisors?

**Comment by oremanj** [comment]
I think this is no longer an issue with simplified nurseries.
