### ISSUE TITLE
Make checkpoint() a public API

### ISSUE THREAD

**Issue by joernheissler** [python-trio/trio#655]
Docs says:

 > it’s useful to know that await trio.sleep(0) is an idiomatic way to execute a checkpoint without doing anything else

I think it would be cleaner to add an explicit `checkpoint` function:
```python3
await trio.checkpoint()
```

**Comment by belm0** [comment]
I don't have a strong opinion about it, only will note that this is contrary to #310 which proposes to expand idiomatic uses of `sleep()`.

**Comment by belm0** [comment]
#310 was expanded to include this matter so please discuss there-- thank you!

**Comment by njsmith** [comment]
Yeah, see https://github.com/python-trio/trio/issues/310#issuecomment-419682884

I'll note also that in the meantime, there is a `trio.hazmat.checkpoint`. (There's nothing hazardous about it, it's just grouped together with the other low-level task suspension routines.)
