### ISSUE TITLE
Come up with a better name for "yield points"

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#66]
I wanted something different from "cancel point" and "schedule point", because sometimes it's useful to be able to talk about those as separate things, but while writing the tutorial I'm realizing "yield point" is a pretty bad example of taking a word that makes sense internally and exposing it to the public. From a user's point of view, generators and async generators have yield points, not regular async functions... (and heck, even internally, for efficiency reasons we might end up not yielding at every yield point).

Ideas:
* schedule point (and accept the ambiguity)
* intervention point
* interaction point
* preemption point (a bit confusing since we're "non-preemptive")
* magic point 😛 
* ...

Dislike: suspension point (often the task is not suspended)

**Comment by hrwaelle** [comment]
I think interaction point is the best choice

**Comment by dimaqq** [comment]
* wait point
* rest stop 😆 
* context switch

Just my 2c, whatever seemed missing from the list...

**Comment by njsmith** [comment]
Maybe "check point"

**Comment by welchbj** [comment]
What about a "flow junction"?

**Comment by sietse** [comment]
I think *yield point* may actually be a good phrase -- not because of the internal `yield` keyword, but because the task yields control to the trio scheduler. Try this on for size -- it's a rewriting of the ['a yield point is two things'](https://trio.readthedocs.io/en/latest/reference-core.html#yield-points) bit. 

> At a yield point, the task briefly yields control back to the trio scheduler (usually `trio.run()`). Two things happen at a yield point:
> 
> 1. The task yields control to the trio scheduler, which then has the option of switching to a different task. (Currently, this scheduler is very simple: it simply cycles through all the runnable tasks, running each one until it hits its ~first~ next yield point. But this might change in the future.)
> 
> 2. The task resumes, and should check for cancellation. The trio scheduler at some point returns control to the task -- but things may have happened while the task was suspended. Especially, the task may have been cancelled. If that matters to you, After a yield point is a good time to check for cancellation, and potentially raise a Cancelled error. See \[Cancellation and timeouts] below for more details.

The bit about cancellation needs improvement, because from the docs I only understood how to use the `with trio.move_on_after(timeout=...)` block -- I couldn't find an example of how to check for cancellation yourself.

**Comment by njsmith** [comment]
@sietse: "yield point" is great in isolation -- the problem is that it does conflict with the python "yield" keyword, and we use it in an almost-but-not-quite-entirely-different way, which is confusing. I'm currently leaning towards switching to "check point"...

Regarding cancellation: sounds like we need to clarify the docs! The way you check for cancellation is exactly by executing a yield (/check) point. That's the whole point: a yield point might switch to another task, and it might raise `Cancelled`. If you want to check for cancellation manually, you can insert an explicit yield point with `await trio.sleep(0)`. (And there's also `trio.hazmat.yield_if_cancelled`, but don't use that – it's really only there as a primitive to use as part of constructing a yield point in complicated cases. The general goal is to keep things simple by replacing the two concepts of "schedule point" and "cancel point" with a single concept that encompasses both of them. For more details, see [this section of the design docs](https://trio.readthedocs.io/en/latest/design.html#cancel-points-and-schedule-points).)

**Comment by ChrisBarthol** [comment]
I like 'checkpoint' like a roadblock, a point of inspection.  Other suggestions I have are 'waypoint' or 'spot check'.

**Comment by njsmith** [comment]
I'm going for "checkpoint" for now – see #113.
