### ISSUE TITLE
Thought while reading docs.

### ISSUE THREAD

**Issue by Carreau** [python-trio/trio#69]
Miscs:

- You dooo mention coroutine ! :-) 
- open_nursery feel weird, I like your NurseryManager.  Or static method on Nursery? 
```
with Nursery.open() as n: 
   ...
```

- Could IPython (as interactive REPL) have an AST-checker to check you `await` all coroutine  and help with potential mistakes ?

**Comment by njsmith** [comment]
> You dooo mention coroutine ! :-)

*shhhhh*

> open_nursery feel weird, I like your NurseryManager. Or static method on Nursery?

I don't think this is going to change at this point -- after a few months of usage it still seems fine to me, and the name is part of a general convention for functions that open a resource with a bounded lifetime that go in a with block (`trio.open_cancel_scope`, `trio.open_file`, `trio.open_tcp_stream`, ...).

> Could IPython (as interactive REPL) have an AST-checker to check you await all coroutine and help with potential mistakes ?

That's a neat idea. I think it's basically https://github.com/ipython/ipython/issues/9251? You could talk to the author of that bug maybe ;-)
