### ISSUE TITLE
getaddrinfo failing with simultaneous requests

### ISSUE THREAD

**Issue by merrellb** [python-trio/trio#716]
I get this error randomly (but consistently) on my Macbook (on my home network) but so far have NOT got had the issue when running on Ubuntu 18.04 on GCE.
```
...
"/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

The fact that most of the requests succeeds leads me to suspect my home router DNS can't keep up with the getaddrinfo requests.  However the error isn't quite what I would expect if the the router was rejecting DNS lookups.

my attempt at a minimal reproduction:
```
async def http_get(url_queue):
    while True:
        host, port, url = await url_queue.get()
        client_stream = await trio.open_tcp_stream(host, port)

async def parent():
    async with trio.open_nursery() as nursery:
        url_queue = trio.Queue(100)
        for i in range(50):
            nursery.start_soon(http_get, url_queue)
        for i in range(1000):
            await url_queue.put(("httpbin.org", 80, "/xml"))

trio.run(parent)
```

**Comment by njsmith** [comment]
Huh, that is weird.

My home router flakes out on code like this. Its failure mode is a little different: if a program calls `getaddrinfo` in quick succession like this, then it drops some of the request packets; eventually (like after a second or more) `getaddrinfo` notices that it's not getting a reply and re-sends the request, and eventually succeeds. This is using glibc's `getaddrinfo` implementation on Linux. So... it's plausible to me that it's your router being bad.

The way I verified that it was the router was to use wireshark to capture outgoing traffic from my laptop. I could see all the DNS requests correctly being sent, and then nothing coming back, the eventual retries, etc. That's what I'd suggest as the next thing to try.

**Comment by oremanj** [comment]
Closing this since I don't see an action item for us.
