### ISSUE TITLE
Documentation should have previous and next button on top as well as bottom.

### ISSUE THREAD

**Issue by RatanShreshtha** [python-trio/trio#726]
I have been going through the trio documentation and I have noticed that the page is really big and if someone just wants to get from one page to either previous or next then he/she will have to scroll down to the bottom of the page then click the next or previous button.

It would be nice to have previous and next button on top as well as on bottom so that anyone can navigate through the documentation more easily.

**Comment by njsmith** [comment]
That would be nice, yeah. We're currently using the theme `sphinx_rtd_theme` (+ some custom CSS tweaks)... and [it sounds like](https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html) we can do this by adding `'prev_next_buttons_location': 'both'` to our `html_theme_options`?

@RatanShreshtha Want to try putting together a PR to do that?

**Comment by RatanShreshtha** [comment]
@njsmith Yeah I am putting together a PR for the same.
