### ISSUE TITLE
High-level networking interface

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#73]
We should have something that's just a smidge higher level than `trio.socket`. This is something that could go into an external library, but:

* I'd like to do TLS at this layer (so it's not bound to socket objects specifically), and in 2017 it really feels like TLS should be an included battery
* Getting started with a simple echo server shouldn't require boilerplate or third-party extensions
* I'm feeling the need for a basic stream abstraction in downstream libraries, and there are interoperability benefits to defining that in `trio` itself

The goal wouldn't be to compete with like, all of netty or twisted or something, but just to provide some minimal extensible abstractions for endpoints, connecting, listening. Maybe UDP too, though that can wait.

Things that should be easy:

* Connecting to a given hostname+port, with ipv4/ipv6 taken care of (ideally with happy-eyeballs)
* ...same as above, but with TLS enabled
* Making a simple server that listens on both ipv4 and ipv6
* Making a simple server that listens on a unix domain port

Maybe:
* Plugging in some code to handle systemd socket activation
* Plugging in some code to do something sensible with the [haproxy PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt)

A source of inspiration is twisted's "endpoints": [tutorial](https://twistedmatrix.com/documents/current/core/howto/endpoints.html), [list of client endpoints](https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IStreamClientEndpoint.html), [list of server endpoints](https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IStreamServerEndpoint.html), [a much fancier server endpoint](https://txacme.readthedocs.io/en/stable/). I'm not a big fan of the plugins + string parsing thing, just because of the whole injecting-arbitrary-code-into-people's-processes thing that plugins do ... though I see the advantage when it comes to exposing this stuff as part of a public interface and wanting it to be extensible there.

We probably want:

* A basic Stream API. There's a sketch in `trio._streams`. This is useful in its own right; the idea would be to implement TLS as a stream wrapper e.g., and we can use a `SendStream` and `RecvStream` for subprocess pipes, etc.

* Some sort of connect and listen factories for streams.

Lots more TBD; for now this is a placeholder to think more about.

Related: #9 (tls support), #13 (more ergonomic server quick-start), #14 (batched accept), #72 (socket option defaults – some might make more sense to set as part of the high-level interface)

**Comment by njsmith** [comment]
When it comes to unix domain socket handling, some references:

* A tricky issue that asyncio ran into: https://github.com/python/asyncio/issues/425
* Twisted: https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/unix.py#L290
* Tornado: https://github.com/tornadoweb/tornado/blob/master/tornado/netutil.py#L215

**Comment by brettcannon** [comment]
A survey of various HTTP libraries to tease out the commonality among their request and response APIs: https://drive.google.com/open?id=1HKHvyeEnB_y4rvLEOraE0JNCcpkVCTJ_jVdKs8KFXYw

**Comment by njsmith** [comment]
Twisted's code for calling `accept` also contains a significant amount of [hard-earned wisdom](https://github.com/twisted/twisted/blob/1607ce663ab40840c44c82df83e26903c48328e7/src/twisted/internet/tcp.py#L1033-L1066).

**Comment by njsmith** [comment]
[moving this comment from #8 because it's more relevant here]

Poorly organized thoughts on server API:

`Listener` is an `AsyncResource` with `start` (returns an arbitrary value, does setup, like `__init__` but async) and `accept` (returns an arbitrary value that is usually a `Stream`, all we actually care about is that it has a `forceful_close` method). `start_server` starts the listener, spawns a task to loop on `accept`, and returns `(start_return_value, task_object)`. The former is to let you get back information from the setup code (example: what port are you actually listening on?), and the latter is b/c fancy supervisors will need to know it, to know which thing needs restarting when a task dies. (Or I guess the return value could be some information on the listener object, and we could pass back the listener object itself directly? Or return a `Server` object with a `.listener` attribute and stuff like close methods?)

Maybe `start_server` should take a mandatory timeout argument (can be `inf` if you want), use `graceful_close` on the passed in strings, and pass in a cancel scope to every callback along with the stream? Because if you *need* to have a timeout on network code, and you *need* that timeout to encompass the `graceful_close` call, then every connection callback has to start with a double-indent boilerplate `with open_cancel_scope: async with stream: ...`, and who wants that?

It should also optionally let you set the listener nursery and the connection nursery separately.

Implementations: `TCPListener`, `UnixListener` (I guess this is ambiguous between STREAM and DATAGRAM sockets... maybe Accepter or StreamListener would be better?), `SSLListener` (wraps another listener), probably eventually `HAProxyListener` (need some way to pass back peername etc. on the stream – maybe `SocketStream` should have methods that return `(type, family, proto, python-style sockaddr)`?), `AcmeListener`, ...

Convenience functions: `start_tcp_server` (with optional SSL), `start_unix_server` (with optional SSL?)

**Comment by njsmith** [comment]
On further thought, I'm wondering if perhaps we should *not* try to handle every weird error that can happen in `accept`. Specifically:

There are some errors that are "normal" – mostly around cases where something goes wrong on the new connection before we accept it. So e.g. the Twisted and Tornado comments say BSD can give ECONNABORTED when the client does a handshake and then sends FIN or RST before we call `accept`, which is... ok? whatever? we can just ignore this, or possibly return a fake stream that errors out, but probably simpler to just ignore it. It's not a problem, anyway. The Linux `accept` manpage also claims that any error you can get on a connection, you can also get here, so like `ENETDOWN` and similar nonsense. That's fine, whatever, same issue as above. (And this is apparently not common, since neither Twisted nor Tornado even attempts to handle it...)

Then there are errors that indicate a system problem, like `EMFILE` or `ENOBUFS`. Twisted handles this by logging something and then carrying on. This has two problems: (a) I'd rather not bind trio itself to any particular logging solution, and (b) if there are no fd's, then the pending connections are probably doomed, but by just leaving them sitting in the accept queue the clients get poor QoS. Libuv handles this using a sneaky trick: it keeps an allocated-but-unused fd around, and if it gets EMFILE, it closes that fd to hopefully put the process below the fd limit, so it can call `accept`, and then it calls `accept` a bunch of times and immediately closes all the sockets it gets, to clear out the accept queue and avoid leaving clients hanging until they timeout. Of course this is complicated and fragile (what if another thread opens an fd while we're doing it? what if we can't re-allocate the 'spare' fd at the end, do we need to remember to do that later?).

The alternative is: if we hit `EMFILE` or similar, crash the listener and let the supervisor restart it! So this means closing the listen socket, which is... pretty reasonable, actually; it immediately and reliably signals to all waiting clients to go away, like the libuv trick without the trickiness. And if any new connection attempts come in while we're restarting, then well, we're breaking under the load, rejecting their connections is pretty reasonable. Similarly, if restarting the listener fails because we can't allocate an fd for the listening socket, then oh well, if we're that short on fds then we can't call `accept` anyway so what good is a listening socket. And by shoving the problem off onto the supervisor, then logging becomes their problem.

**Comment by njsmith** [comment]
Okay, more refined thoughts on the issue about how to handle resource exhaustion errors (EMFILE etc.) in servers:

For the `Listener` interface, I'm going to let these errors escape. This allows the caller to respond appropriately, and that's definitely more sensible than hard-coding the handling inside `accept` itself.

For our `spawn_tcp_server` or whatever we end up calling it... I'm still unsure :-(. "Just crash" is problematic when we don't actually have any existing supervisors or experience with them. And if you're binding to a random ephemeral port, then restarting is very much a state-changing operation, unless you have some way to pass the port number across restarts.

**Comment by njsmith** [comment]
Reviewed some erlang libraries to see how they handle capacity errors:

* [ranch](https://github.com/ninenines/ranch/) (used by [cowboy](https://github.com/ninenines/cowboy) handles EMFILE by (a) logging a message, (b) sleeping 100 ms. Other `accept` errors are just ignored: https://github.com/ninenines/ranch/blob/55c2a9d623454f372a15e99721a37093d8773b48/src/ranch_acceptor.erl#L41

* Yaws seems to crash the acceptor process when it gets EMFILE, ENFILE, or other errors: https://github.com/klacke/yaws/blob/59bbfd912c0bffa9d9c1f2a149ddfc420895f596/src/yaws_server.erl#L1151-L1165

* Mochiweb seems to (a) sleep 100 ms, (b) log an error, (c) crash the acceptor loop: https://github.com/mochi/mochiweb/blob/23dc11959affd9b0849c2ac0ff4200c1c82aa80c/src/mochiweb_acceptor.erl#L57-L73

* Misultin logs and otherwise ignores all errors from `accept`: https://github.com/ostinelli/misultin/blob/b9fe3125cf17f4415a6d7fc60642b670f5e18eb8/src/misultin_acceptor.erl#L141

* The HTTPD server in the "inets app" (ships with Erlang/OTP, I guess it's their version of `SimpleHTTPServer`) handles EMFILE and ENFILE by silently sleeping for 200 ms: https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/lib/inets/src/http_server/httpd_acceptor.erl#L161-L167 (their [ssh server](https://github.com/erlang/otp/blob/83e20c62057ebc1d8064bf57b01be560cd244e1d/lib/ssh/src/ssh_acceptor.erl) seems to do the same)

Also, I'm not 100% sure, but I think mochiweb and actually open the accept socket outside of the acceptor process, so crashing the process just causes a new process to be spawned using the same socket.

**Comment by brettcannon** [comment]
Is there a library named "actually"? Or did you mean to say "actually opens" instead of "and actually open"? Or is there a word missing?

**Comment by njsmith** [comment]
Whoops, I meant mochiweb and yaws, the two libraries that do crash their acceptor process. Thanks for the catch.

**Comment by brettcannon** [comment]
@njsmith I went ahead and edited your comment to add yaws.

**Comment by njsmith** [comment]
I ended up copying the "log and wait 100 ms" thing that the erlang servers do, we'll see how it goes. It's just using the stdlib logging, on the theory that well, it kinda sucks, but as methods of dumping to stderr go, at least it's reconfigurable and good logging packages will have some easy way to capture it.

Follow-up bugs:

* #280 – High level API for accessing `getsockname()` / `getpeername()` – needed for PROXY support
* #279 – unix domain helpers
* #275 – setting a source interface in `open_tcp_stream`
