### ISSUE TITLE
PyCharm cannot see trio.current_time

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#770]
PyCharm highlights references to `trio.current_time`, warning: `Cannot find reference 'current_time' in '__init__.py'`

**Comment by belm0** [comment]
likely related to this in `_core/__init__.py`:
```
# TODO:  make the _run namespace a lot less magical
from ._run import *
```

**Comment by belm0** [comment]
`current_time` uses the thread-local-context-as-global magic

it's a frequently used function in the API, so the IDE warnings are noticeable

**Comment by njsmith** [comment]
See #542 for the full epic saga of fixing this.

Are you on the latest release? I thought the fixes for `trio.*` at least were released already, though i might be misremembering.

**Comment by belm0** [comment]
Yes, seen on 0.9.0

**Comment by njsmith** [comment]
Interesting -- 0.9.0 does have an explicit `from ._core import current_time` ([ref](https://github.com/python-trio/trio/blob/v0.9.0/trio/__init__.py)), which is enough for jedi to offer it for completion, but I guess pycharm is more picky and wants to be able to track that back to the actual definition. Sorting that out is on the todo list in #542, but it will require a bit of work to replace the magic `exec` in `trio/_core/_run.py` with static code generation.
