### ISSUE TITLE
Better expose Nursery and TaskStatus for type annotations

### ISSUE THREAD

**Issue by goodboy** [python-trio/trio#778]
As per some [gitter banter](https://gitter.im/python-trio/general?at=5bef93919f5a9e6e41f9b0b4) we should more publicly expose the `Nursery`, `CancelScope` and `Taskstatus` types for use as [type annotations](https://www.python.org/dev/peps/pep-0484/).

Currently client code is stuck importing most of these from internal private modules which leads the following beauty:
```python
async def _async_main(                                                                                                                                                                              
   self,                                                                                                                                                                                           
   accept_addr: Tuple[str, int],                                                                                                                                                                   
   arbiter_addr: Optional[Tuple[str, int]] = None,                                                                                                                                                 
   parent_addr: Optional[Tuple[str, int]] = None,                                                                                                                                                  
   task_status: trio._core._run._TaskStatus = trio.TASK_STATUS_IGNORED,                                                                                                                            
) -> None:
     ...
```

Worth noting:
- `CancelScope` may already be exposed soon via python-trio/trio#607
- @njsmith and @Fuyukai already seems interested in adding them internally as per python-trio/trio#543

**Comment by tgoodlet** [comment]
Oh, and let's not forget about the very important [`Task`](https://github.com/python-trio/trio/blob/master/trio/_core/_run.py#L552)!

**Comment by oremanj** [comment]
`Task` is already public as `trio.hazmat.Task` -- how were you envisioning it getting more public?

For now I recommend using the `Nursery` and `TaskStatus` exposures in `trio-typing`. When we bring the type hints into Trio proper (#543), I imagine a resolution to this issue will go along with it. I'm going to close this for now, but leave a pointer at #543.
