### ISSUE TITLE
SocketListener ignores peer address

### ISSUE THREAD

**Issue by adontz** [python-trio/trio#839]
Currently SocketListener ignores peer address returned socket.accept

https://github.com/python-trio/trio/blob/b20862412b98147f03ba8d7c110398107f649839/trio/_highlevel_socket.py#L371

What is rationale behind this and what can be done to receive this information?

**Comment by pquentin** [comment]
I think @njsmith forgot to hit on the close button, so doing that now. Again, feel free to reopen!

**Comment by njsmith** [comment]
Whoops, thanks for the catch :-)
