### ISSUE TITLE
Add a `.timeout` attribute to `CancelScope`?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#861]
Now that `CancelScope`s are becoming more exposed to users with #607 / #835, it occurred to me that it might be nice to have a weird magical `.timeout` property on them. The definition would be:

```python
@property
def timeout(self):
    return max(0.0, self._deadline - trio.current_time())

@timeout.setter
def timeout(self, new_timeout):
    self.deadline = trio.current_time() + new_timeout
```

**Comment by njsmith** [comment]
...Of course as soon as I posted that I realized there's a probably-fatal flaw. This code looks all nice and sensible:

```python
cancel_scope.timeout += 1
```

But with the definition above, it would call `current_time()` twice, so it would actually cause the deadline to increase by slightly more than 1 second, which seems like a super obscure gotcha.

**Comment by smurfix** [comment]
Well, we could always create `.timeout` as a magical int-derived object that actually supports __iadd__ by updating its parent … though that would have interesting overhead (and require a weakref). Let's just add a `.timeout_after` method (or whatever the name shall be) instead.

**Comment by njsmith** [comment]
I'm not convinced there's anything better to do here than what we're already doing. We can always re-open later when we have more experience with the new `CancelScope` APIs.
