### ISSUE TITLE
Cannot use async generators from coroutines

### ISSUE THREAD

**Issue by carlopires** [python-trio/trio#871]
Newbie here. I just started porting some code from eventlet to trio. I'm using python 3.6.2 and trio 0.10.0.

*test.py*
```python
import time
import argparse
import trio


class Counter():
    def __init__(self):
        self.value = 0
        self.lock = trio._sync.Semaphore(1)
    
    async def inc(self):
        async with self.lock:
            await trio.sleep(1)
            self.value += 1
    
    def get(self):
        return self.value


async def counter(interval=5):
    co = Counter()
    time_start = 0

    while 1:
        now = time.time()

        if now - time_start > interval:
            await co.inc()
            time_start = now

        yield co.get()
        

async def test_counter(step, co):
    n = await co.__anext__()
    print(f'step: {step}, counter: {n}')


async def test(steps):
    co_gen = counter()

    async with trio.open_nursery() as nursery:
        for step in range(steps):
            nursery.start_soon(test_counter, step, co_gen)
        
    print('all done')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('steps')
    args = parser.parse_args()
    trio.run(test, int(args.steps))
```
It works if I run it with no concurrency:
```
$ python3 test.py 1
step: 0, counter: 1
all done
```
Adding concurrency makes it fail:
```
$ python3 test.py 2
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    trio.run(test, int(args.steps))
  File "/opt/py3/lib/python3.6/site-packages/trio/_core/_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "test.py", line 47, in test
    nursery.start_soon(test_counter, step, co_gen)
  File "/opt/py3/lib/python3.6/site-packages/trio/_core/_run.py", line 398, in __aexit__
    raise combined_error_from_nursery
trio.MultiError: AttributeError("'NoneType' object has no attribute 'unwrap'",), StopAsyncIteration()

Details of embedded exception 1:

  Traceback (most recent call last):
    File "test.py", line 38, in test_counter
      n = await co.__anext__()
    File "test.py", line 31, in counter
      await co.inc()
    File "test.py", line 15, in inc
      async with self.lock:
    File "/opt/py3/lib/python3.6/site-packages/trio/_sync.py", line 92, in __aenter__
      await self.acquire()
    File "/opt/py3/lib/python3.6/site-packages/trio/_sync.py", line 467, in acquire
      await _core.cancel_shielded_checkpoint()
    File "/opt/py3/lib/python3.6/site-packages/trio/_core/_traps.py", line 44, in cancel_shielded_checkpoint
      return (await _async_yield(CancelShieldedCheckpoint)).unwrap()
  AttributeError: 'NoneType' object has no attribute 'unwrap'

Details of embedded exception 2:

  Traceback (most recent call last):
    File "test.py", line 38, in test_counter
      n = await co.__anext__()
  StopAsyncIteration
```

I've read some issues related and understood that it seems to be problematic to use async generators from trio tasks. But I'm not sure about what is wrong here.

**Comment by njsmith** [comment]
> I've read some issues related and understood that it seems to be problematic to use async generators from trio tasks.

The problems you're thinking about only happen if your generator has a `yield` inside a `try` or `with` – especially if the `with` opens a nursery or cancel scope. Your generator doesn't have that, so you don't need to worry about those issues.

I think the problem here is that you're trying to advance the same generator from two tasks at the same time. That's not something that python generators support. I'm not sure what it would mean, even... the generator would have to be in two places at the same time, or something?

You can actually create an similar situation with regular synchronous generators, though it's a bit tricky:

```python
GEN_OBJ = None

def gen_func():
    # We're inside the call to GEN_OBJ.__next__() here
    # and while inside it, we try to call it again
    yield GEN_OBJ.__next__()

# Save the generator object in a global, so the generator can access it
GEN_OBJ = gen_func()
gen_func.__next__()
```

If you try running this, you'll get an error, because python will detect that this doesn't make sense.

Ideally, your code should have gotten that same error. But, unfortunately, there's a bug in how python tracks which async generators are already running: https://bugs.python.org/issue32526

So instead of raising an error immediately, python starts doing some nonsensical thing that eventually crashes.

Since the bug is in Python itself, I don't think there's anything we can do about this on trio's side :-(.

**Comment by carlopires** [comment]
> I think the problem here is that you're trying to advance the same generator from two tasks at the same time. That's not something that python generators support. 

So to get rid of it is enough to protect each call to the generator with a lock? 
```python
async def test_counter(step, co, lock):
    async with lock:
        n = await co.__anext__()
    print(f'step: {step}, counter: {n}')

async def test(steps):
    co_gen = counter()
    lock = trio.Semaphore(1)

    async with trio.open_nursery() as nursery:
        for step in range(steps):
            nursery.start_soon(test_counter, step, co_gen, lock)
        
    print('all done')
```
Output:
```bash
$ python3 test.py 10
step: 7, counter: 1
step: 8, counter: 1
step: 9, counter: 1
step: 6, counter: 1
step: 2, counter: 1
step: 0, counter: 1
step: 1, counter: 1
step: 5, counter: 1
step: 4, counter: 1
step: 3, counter: 1
all done
```
This fixed the issue, but it sounds weird to protect every call to async generators that calls trio tasks with a lock.

**Comment by njsmith** [comment]
> So to get rid of it is enough to protect each call to the generator with a lock?

That's right.

> This fixed the issue, but it sounds weird to protect every call to async generators that calls trio tasks with a lock.

Of course if you have multiple generator objects you can use them at the same time in different tasks. But any individual generator object is a sequential thing: it runs through the function body exactly once, from beginning to end, occasionally pausing until someone resumes it. I'm not actually sure what you expect to happen when trying to call `.__anext__()` twice at the same time on the same object...?

By the way: you know about `trio.Lock`, right? Using a `Semaphore(1)` is a bit unusual-looking here, because you could use a `Lock()` instead.

**Comment by carlopires** [comment]
> any individual generator object is a sequential thing

If there is no threading involved any python code is a sequential thing, trio tasks included, am I right?

So it is not totally correct when you say that I'm trying to advance the same generator from two tasks **at the same time**.

When you have an infinite loop inside the generator it becomes a _producer like_ coroutine with bidirectional communication through `next()` and `send()`. This is a common construction from the code I'm porting, which is based on python2.

What is new for me here is that a call to the generator need to be protected to avoid re-entrance.

So I'm thinking that the right thing to do is to implement a replacement based on trio tasks + channels.

> By the way: you know about trio.Lock, right?

Thanks for pointing out. I'm still reading the docs and learning the library :)

**Comment by njsmith** [comment]
> If there is no threading involved any python code is a sequential thing, trio tasks included, am I right?

Well, like a lot of things in computers, there are multiple ways to think about it :-). At one level you're correct: across a whole trio program (that doesn't use threads), at any given moment there's only one task actively using the CPU, and all the python statements are executed in *some* global sequential order.

But that's not the kind of "at the same time" that I'm talking about here. If we have two tasks running concurrently, then each individual task runs sequentially, in the sense that everything it does happens in order it specifies. But the two tasks run "at the same time" in the sense that they can do I/O operations simultaneously, and all their non-I/O operations get interleaved in some unpredictable way.

Say we have a generator like:

```python
async def my_gen_func():
    total = 0
    while True:
        await trio.sleep(5)
        yield total
        total += 1
```

Now imagine we create an async generator object, `agen_obj = my_agen_func()`. And then we start two tasks running concurrently:

* Task 1 calls `await agen_obj.__anext__()`
* Task 2 waits 0.5 seconds, and then calls `await agen_obj.__anext__()`

The contract of `__anext__` is: it takes a generator that's suspended at one `yield` point, and runs it until it reaches the next `yield` point, then returns.

So task 1 is fine: it starts the generator function executing, and keeps running until it reaches a `yield`, which takes 1 second.

But then here comes task 2. At the moment it calls `__anext__`, the generator isn't at a `yield` point at all – it's in the middle of executing `await trio.sleep(1)`. What do you expect to happen?

(And worse, Imagine if it were a `asend` call – where would the value be sent, even the generator isn't even at a `yield`?)

**Comment by njsmith** [comment]
(Closing this because I don't think there's any todo item for trio currently; feel free to keep chatting though.)
