### ISSUE TITLE
Drop support for early python 3.5.x point releases?

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#880]
We have another issue about when to drop support for 3.5 entirely (#75). This issue is to discuss something narrower: should we drop support for some early 3.5.x releases, while keeping it for later ones?

Possible advantages:

* The semantics of `__aiter__` are totally different in 3.5.0 and 3.5.1 versus 3.5.2. We have to carry around [special hacks](https://github.com/python-trio/trio/blob/3bdd3fd0ea7f26484f42502df96e63c9d75953c9/trio/_util.py#L76-L88) to support those old versions.

  * The hacks themselves are not too terrible to maintain. The biggest issue is that they add more entries to the test matrix, which is extra complexity and getting gradually more difficult (e.g. on Travis we have to fall back to the older `trusty` environment to get access to an old enough Python, and Azure doesn't provide any old 3.5.x's at all.)

* The typing module also went through a lot of changes over the lifespan of 3.5.x. I haven't looked into the details here, but @oremanj [says](https://gitter.im/python-trio/general?at=5c4ba49a975714406b40f4c0) "it looks like 3.5.2 was the first version with a typing module that's even kinda usable for async code". I guess as soon as we start seriously tackling #543 we'll quickly discover the limits!

Possible disadvantages:

* It's easier to explain "we support 3.5 or greater" than to explain "we support 3.5 or greater, except for these micro-versions of 3.5, by the way do you even know what micro-version of 3.5 you're using?"

Who would be affected?

* ~~pypy's 3.5 branch claims to emulate 3.5.3. (And I guess we could convince them to bump that higher if necessary? they also have a 3.6 branch that's in pretty solid shape, but who knows when that will actually release.)~~ pypy's on 3.6 now

* ~~Debian stable [has 3.5.3](https://packages.debian.org/search?keywords=python3)~~ now oldstable has 3.5.3, and stable has 3.7.something.

* Ubuntu 14.04 "trusty" [defaults to 3.4](https://packages.ubuntu.com/trusty/python3), but [has 3.5.2](https://packages.ubuntu.com/xenial/python3.5)

* Ubuntu 16.04 "xenial" has its default python3 as [3.5.2](https://packages.ubuntu.com/xenial/python3.5)

* Ubuntu 18.04 "bionic" defaults to [3.6.7](https://packages.ubuntu.com/bionic-updates/python3)

* On Redhat/CentOS 6 and 7, AFAICT there's no python 3 in the main distro (is this true?), so people use EPEL or Software collections or whatever. EPEL 7 [has python 3.4 and python 3.6, no 3.5 at all](http://mirror.math.princeton.edu/pub/epel/7/x86_64/Packages/p/). EPEL 6 [doesn't have anything newer than 3.4](http://mirror.twinlakes.net/epel/6/x86_64/Packages/p/). Software collections has a variety of versions, including both 3.5 and 3.6. Their 3.5 is **3.5.1**. (See the `rh-python35-python-3.5.1-11.el6.x86_64.rpm` package on [this list](http://mirror.centos.org/centos/6/sclo/x86_64/rh/rh-python35/), and I also installed it in a container to check.)

So it sounds like pretty much everyone who has an officially supported 3.5.anything, has an officially supported 3.5.2+, except that if anyone is using software collections then getting 3.5.2+ requires upgrading to 3.6.

Another source of stats is PyPI downloads: https://pypistats.org/packages/trio. The numbers are pretty noisy because we don't have a lot of downloads, and for these purposes I'm much more worried about people trying to run their first program than heavy users, so the download stats may not be super representative anyway. But it looks like right now our downloads are ~5-10% python 3.5, and most of the rest on newer versions.

**Comment by oremanj** [comment]
It turns out that all the missing `typing` features I care about seem to be in `typing_extensions` (a PyPI package), so I feel less strongly about this than I did previously.

**Comment by oremanj** [comment]
Also, FWIW, mypy itself requires 3.5.2 at minimum.

**Comment by WindSoilder** [comment]
In early days, I found that `python3.5.0` don't provide `typing.Type` class, it can be useful for the https://github.com/python-trio/exceptiongroup/issues/7 
And the CI failure about it lays here:
https://travis-ci.com/python-trio/exceptiongroup/jobs/172449801

**Comment by oremanj** [comment]
We dropped 3.5 support so this question has become moot!
