### ISSUE TITLE
trio.Path.home raises "AttributeError: _flavour"

### ISSUE THREAD

**Issue by zthompson47** [python-trio/trio#960]
I get the following on Mac and Linux:
```
>>> import trio
>>> trio.Path.home()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1055, in home
    return cls(cls()._flavour.gethomedir(None))
  File "/Users/zach/.allotropic/python/default/lib/python3.7/site-packages/trio/_path.py", line 157, in __getattr__
    raise AttributeError(name)
AttributeError: _flavour
```
As the traceback states, ``pathlib.Path`` is instantiating itself to dertermine its ``_flavour``, which is a class to delegate filesystem calls to differing Windows and Posix environments.

I think the explanation is that trio.Path does not override ``__new__``, so it doesn't get a chance to turn into a ``PosixPath`` or ``WindowsPath`` object like ``pathlib.Path`` objects do.  The ``_flavour`` attribute is only available from these system-specific classes, and the ``AsyncAutoWrapperType`` doesn't explicitly wrap these classes to make it an attribute of ``trio.Path``.

One workaround is to override ``home`` in ``trio.Path``:
```
    @classmethod
    def home(cls):
        return cls(cls()._wraps()._flavour.gethomedir(None))
```

There are other approaches and I'd like to check in with the team here.  Any thoughts?

**Comment by njsmith** [comment]
Hmm, looks like a silly bug in `generate_wraps`:

```python
            if isinstance(attr, classmethod):
                setattr(cls, attr_name, attr)
```

So we're just setting `trio.Path.home = pathlib.Path.home`. Obviously this is not going to work, since we pass the wrong `cls` argument, and also it probably needs to be asyncified? (Not 100% sure.) Ultimately I guess we should do something like:

```python
@classmethod
async def home(cls):
    return await run_sync_in_worker_thread(pathlib.Path.home)
```

Except maybe we should generate this instead of writing it manually?

See also: #917, which points out an issue with `.cwd()`. `pathlib.Path` has two classmethods: `home` and `cwd`. So these overlap.

**Comment by zthompson47** [comment]
Thanks for the pointer to ``generate_wraps`` - I hadn't thought about it that way.

I was also considering posting to #917 about making ``home`` async because it could end up with i/o reading the password database in ``pathlib.py``:
```
return pwd.getpwuid(os.getuid()).pw_dir
```
I'll take a look at generating both ``home`` and ``cwd`` classmethods, and for now I'll assume that both of these methods will be async.
