### ISSUE TITLE
how can use motor in trio 

### ISSUE THREAD

**Issue by muzico425** [python-trio/trio#983]
hello，how to use async mongo library in trio？

**Comment by pquentin** [comment]
Hello @muzico425! I see that [motor supports asyncio](https://motor.readthedocs.io/en/stable/tutorial-asyncio.html), but not trio. For such libraries, we suggest to try [trio-asyncio](https://trio-asyncio.readthedocs.io/en/latest/), which allows you to use asyncio libraries on top of trio. Unfortunately, it still has rough edges, so it may not be suitable for your use case.

Does that make sense?

**Comment by muzico425** [comment]
thank you,i will try use trio-asyncio.

**Comment by muzico425** [comment]
and what's async mongo library in trio?

**Comment by pquentin** [comment]
Unfortunately I don't think a trio MongoDB library exists yet!

**Comment by muzico425** [comment]
ok，thank you

**Comment by smurfix** [comment]
That being said, motor basically isn't async mongo, it's a shift-mongo-to-threads wrapper. You can adapt it with trio_asyncio, or you can just run the pymongo calls in a thread yourself (trio has the tools for doing that) which is about the same amount of annoying boilerplate but should be quite a bit faster. 

Motor does do a few nice things like pushing `find()[index]` and similar slicing operations to the server and managing concurrent access to the connection(s), but if you don't need that …
